### ISSUE TITLE
Move the cursor one word to the right, symbol "|" not reported

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#10855]
This case occurs in NVDA_2019.3.1. While pressing ctrl + right arrow to move the cursor one word to the right, symbols are not reported. E.G. "|"

### Steps to reproduce:
1. Open notepad.
2. Paste text 
| 0 | 1 | 2 | 3 |
3. Press ctrl + right arrow several times to move the cursor one word to the right.
#### Actual behavior:
Symbols "|" are not reported.
#### Expected behavior:
NVDA reports "bar"

#### NVDA Installed/portable/running from source:
Installed. / portable

#### NVDA version:
2019.3.1

#### Windows version:
Windows version 10.0.18363

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
NVDA_2019.2.1 works as expected.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by DrSooom** [comment]
@surfer0627: Which TTS synthesizer is used? And please take a look at the chapter "12.2.2. Punctuation/symbol pronunciation" in the NVDA User Guide.

**Comment by surfer0627** [comment]
@DrSooom 

> Which TTS synthesizer is used?

Windows OneCore / eSpeak

 > And please take a look at the chapter "12.2.2. Punctuation/symbol pronunciation" in the NVDA User Guide.

Yes . How to change pronunciation settings to solve this issue?

**Comment by DrSooom** [comment]
Quote from the NVDA User Guide (version: 2019.3):
> - Using the Level field, you can adjust the lowest symbol level at which this symbol should be spoken. 
> - The Send actual symbol to synthesizer field specifies when the symbol itself (in contrast to its replacement) should be sent to the synthesizer. This is useful if the symbol causes the synthesizer to pause or change the inflection of the voice. For example, a comma causes the synthesizer to pause. There are three options: 
>    - never: Never send the actual symbol to the synthesizer. 
>    - always: Always send the actual symbol to the synthesizer. 
>    - only below symbols' level: Send the actual symbol only if the configured speech symbol level is lower than the level set for this symbol. For example, you might use this so that a symbol will have its replacement spoken at higher levels without pausing, while still being indicated with a pause at lower levels. 

Filter for "|" in this dialog and change these parameters. Maybe it solves your issue.

**Comment by feerrenrut** [comment]
#12695 reverts #11856 thus re-opens this issue.

**Comment by CyrilleB79** [comment]
It is indicated that #12710 (not yet merged) should fix this issue.
However, this issue as described in the "steps to reproduce" is fixed since NVDA2020.3 (probably by #11167).
For clarity, it would be really better to close this issue and to open a new one describing exactly what #12710 fixes.
Cc @feerrenrut

**Comment by feerrenrut** [comment]
>It is indicated that https://github.com/nvaccess/nvda/pull/12710 (not yet merged) should fix this issue.

#12710 was an alternative approach to fixing this issue. It intends to be a more generic fix for the same problem and several others.

While the initial described problem (a single bar character) has been fixed since NVDA2020.3 (probably by https://github.com/nvaccess/nvda/pull/11167). The more general problem remains, consider two bar characters.
This issue probably needed some grooming, I have updated the description.

**Comment by CyrilleB79** [comment]
Yes thanks for the updated description. All is clear now.

**Comment by Adriani90** [comment]
I know this issue talks about a specific symbol, though i would like to draw the attention to the word navigation in general
Current status with NVDA 2024.4.1:
Assume follwoing text
1. | 2, hello arpegio() || bow

1. Open NVDA
2. Navigate the text above with ctrl+right and left arrows between 1 and bow, both in browse mode, object model, ritch edit areas in focus mode.

a) Actual with focus mode in Firefox:
* The paranthesis and the double bar are focused but not reported on ctrl+right arrow (this is valid for all cases where multiple symbols are written consecutively)
* The bars are in general skipped when pressing ctrl+left arrow.
* Symbols such as dots, or commas, or question marks etc. are merged with the word and cannot be navigated separately by ctrl+arrow left and right.
* When random symbols are mixed together (e.g. .,?![|), only the first symbol from the symbol chain is reported.
* Words in parathesis like (hello world) are reported as if there was no paranthesis at all.

b) Actual with browse mode in Firefox:
* Same behaviors as explained in a) except that the bar symbols are not skipped on ctrl+left arrow.
cc: @jcsteh 

c) Actual in Chromium with focus mode:
* The bars are reported as expected and they can be navigated by ctrl+left and right arrow
* Paranthesis are focused but not reported (same as a))
* Dots, commas, question marks etc. are navigable with ctrl+left and right arrows if they stand alone.
* Multiple dots, or commas, or question marks etc. in a row are merged to one word when navigating with ctrl+left and right arrow
* When random symbols are mixed together (e.g. .,?![|), only the first symbol from the symbol chain is reported.
* Paranthesis around a word can be navigated separately with ctrl+left and right arrow.

d) Chromium in browse mode:
* Same as b)

cc: @aleventhal

e) MS Word or Notepad:
* Same as c), except that double bars are not reported at all

This issue arises due to unicode definition of word and individual definition of words in other applications, but this is controversial especially when reading long numbers with separators or other languages where there is no space character between sentences or where symbols play a very important role such as in asian languages.

My conclusion is that there is only one way to achieve consistent word navigation within all use cases:
* Add a check box in NVDA (disabled by default) that skips symbols entirely on word navigation when enabled, or navigates every symbol as a single word when disabled (could be "skip symbols on word by word navigation checkbox")
