### ISSUE TITLE
nvWave: Use Windows Audio Session API

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#11615]
### Is your feature request related to a problem? Please describe.
NVDA lags due to the old Waveout API. Moreover, not turning the device off to solve this problem is costly for mobile computers.
### Describe the solution you'd like
A modern API named as Windows Audio Session was introduced in Windows Vista. NVDA supports Windows 7 and newer, so it is Windows Audio Session API can be used without any problem.
### Describe alternatives you've considered
WASAPI provides more flexibility for us, so we can use the standard device behaviours without a customization.
### Additional context
Important note: There are signs for Waveout's removal. We must prepare for future Windows releases now.

**Comment by josephsl** [comment]
Hi, we need to consider two things: synthesizers and an actual documentation 9or an equivalent proof in the Windows SDK) that waveout is going away. Thanks.

**Comment by akash07k** [comment]
However, I second this. WASAPI is more versatile and future proof.
Moreover, there's very high probability that it will increase NVDA's
responsiveness across devices.
I agree with Joseph's point though

**Comment by leonardder** [comment]
There is a related issue regarding moving NVWave to c++: #5096

**Comment by feerrenrut** [comment]
This is certainly something we have discussed internally, and even suggested as a project for GSOC, I'm surprised if there isn't already an issue for it. 

I think it is easy to justify this change, but I would like to question the following:
> not turning the device off to solve this problem is costly for mobile computers.

I wasn't able to find any data / reference that indicates that calling `waveOutOpen` results in the computer entering a state where it uses more power. 

Docs reference:
https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-waveoutopen

**Comment by OzancanKaratas** [comment]
Do we have to switch to C to use WASAPI? Can't we do this using Python?

**Comment by feerrenrut** [comment]
@OzancanKaratas I would assume it is not necessary until there is some evidence to the contrary.

**Comment by beqabeqa473** [comment]
i don't think so, as there are objective prediction that this might
improve nvda's performance in terms of sound output.

On 9/21/20, Reef Turner <notifications@github.com> wrote:
> @OzancanKaratas I would assume it is not necessary until there is some
> evidence to the contrary.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11615#issuecomment-696123096


-- 
with best regards beqa

**Comment by OzancanKaratas** [comment]
I agree with @feerrenrut, instead of moving to C for WASAPI, we should use all the possibilities we have for the existing Python library. How can we work together?

**Comment by leonardder** [comment]
I've done several WASAPI based stuff in Python for @babbagecom that was using the volume control APIs in WASAPI. This was pretty hacky with comtypes because IDispatch isn't supported on these interfaces. I'm certainly not the expert here, But i'm tempted to advice the C++ route here, especially with having headers in the Windows 10 SDK out of the box. The only thing that would need to be thought out correctly is how to do the interop with Python.

**Comment by OzancanKaratas** [comment]
So this means we have to rewrite nvWave completely. This can be difficult. I think @michaelDCurran should participate in this discussion.

**Comment by feerrenrut** [comment]
> pretty hacky with comtypes because IDispatch isn't supported on these interfaces. 

I see, thanks @leonardder 

It's quite likely that much of nvWave will have to be re-written anyway. Part of this work will require defining an appropriate boundary between our python code and the WASAPI interfaces.

**Comment by OzancanKaratas** [comment]
@feerrenrut, I think you should pin this issue so that everyone can see. A non-visually impaired user may would like to convert the Python code to C++. We need help.

**Comment by leonardder** [comment]
I'm not convinced that this issue is that important that it requires pinning it. Could you provide some rationale as why you think so?

**Comment by OzancanKaratas** [comment]
People who want to tackle this issue need to be aware of it.

**Comment by josephsl** [comment]
Hi, I know the following may sound harsh, but making people aware of the work to port nvwave to C++ and improve the overall infrastructure may not be a solid justification. At least people might be aware as to the difficulty that lies ahead, but that doesn’t mean it will bring noticeable benefits to NVDA, especially when considering that audio performance can be a factor in people choosing what to use. A justification that goes into details as to how Windows Audio Session can benefit NVDA users in the short-term and long-term could persuade contributors to investigate possibilities, but justifying WAS in terms of programming languages is, to me at least, not quite convincing. Thanks.

**Comment by OzancanKaratas** [comment]
I found a library worth checking out [Here](https://github.com/bastibe/SoundCard)!

**Comment by Adriani90** [comment]
Could this maybe make a difference when working on a virtual machine? The audio performance there is significant and NVDA suffers from speech crackling problems. I have this problem for example on a Xen Desktop Virtual machine created through the Citrix virtualization environment.

**Comment by josephsl** [comment]
Hi, I would say no, as it is specific to latency created by virtual hardware. You can test this playing music or videos on the virtual machine with and without NVDA running. Thanks.

**Comment by OzancanKaratas** [comment]
Latency may be shorter. However, you will experience the disadvantages of running a virtual machine.

**Comment by Adriani90** [comment]
I know, but there is not the question of advantages or disadvantages, when it comes to security policies in companies then you don’t have a choice as an user.

 

 

Von: Ozancan Karataş <notifications@github.com> 
Gesendet: Mittwoch, 4. November 2020 22:26
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] nvWave: Use Windows Audio Session API (#11615)

 

Latency may be shorter. However, you will experience the disadvantages of running a virtual machine.

**Comment by leonardder** [comment]
I think I got a good personal reason to invest in this. I got a corporate laptop (Latitude 5401) that has a bug in its soundcard driver blowing up the memory usage to infinite in around half an hour. After days of debugging, including a complete reinstall, it turns out that NVDA is the culprit. As soon as I route NVDA audio through a USB headset, memory usage is normal.
Note that I can also reproduce this with NVDA 2020.2, so no relation with https://github.com/nvaccess/nvda/issues/10721

**Comment by leonardder** [comment]
Did some additional research. Note that there's some ongoing work in this area, namely an initiative to create modern C++ projections for the Win32 API, see https://github.com/microsoft/cppwin32 . That will probably make interfacing against WASAPI a whole lot easier, as the projections are likely to take care of all the com stuff under the hood.

**Comment by jcsteh** [comment]
While WASAPI certainly allows for lower latency, cleaner implementation and probably better CPU utilisation, note that WinMM (what NVDA currently uses) is [implemented as a layer on top of WASAPI](https://stackoverflow.com/questions/11755261/is-directsound-and-winmm-based-on-wasapi). So, switching to WASAPI alone is not going to solve problems we're seeing with audio drivers; e.g. truncated speech, memory leaks, etc. At the end of the day, the audio is sent to the driver the same way regardless of whether we use WinMM or WASAPI.

I'm not suggesting this isn't worth doing; on the contrary, I think it probably is. However, please don't see this as a silver bullet that is going to solve all the audio things. That just isn't accurate.

All of that said, switching might make working around some of these issues easier, especially given the age, complexity, locking, etc. of our existing nvwave code.

**Comment by OzancanKaratas** [comment]
@leonardder, Windows Audio Session uses IUnknown interface, not IDispatch. I am not an expert. What do you think we can do?

**Comment by jcsteh** [comment]
It probably makes most sense to implement this in C++ and export our own
functions to ctypes. It might theoretically be possible to implement the
whole thing in Python, but it'd be painful to write out all the interfaces,
plus there are probably efficiency advantages in an area like this to doing
it in C++.

**Comment by jcsteh** [comment]
I started playing with this in a [branch](https://github.com/jcsteh/nvda/tree/wasapi). It's still in the very early stages of development:

1. It only uses the default audio device and won't recover if it disappears.
2. Indexes don't work properly yet. I'm not sure why yet; I've added code to support this, but it isn't working.
3. Strangely, eSpeak seems to have less high frequency response, despite running at the same sampling rate. I'm not sure what's going on there yet.
4. The code needs cleanup and comments.

As I expected, this doesn't really seem to improve latency. However, I'm hoping it might resolve some occasional deadlocks and other quirks in the old code, as it's quite a bit cleaner.

**Comment by leonardder** [comment]
@jcsteh This is awesome. Can you say anything about improvements in the Dell driver memory leak issue you, I and others are suffering from?

**Comment by jcsteh** [comment]
I can't say whether it would have helped with that issue because that bug has finally been fixed in the Dell drivers, at least for my machine (XPS15 9510).

**Comment by leonardder** [comment]
Ah that's interesting. Kinda offtopic here, but could you please provider your driver version and date for reference? It will be especially helpful for people like me fighting this bug. I installed the newest (XPS15 9510) driver on my somewhat older latitude but unfortunately, memory issues still occur.

**Comment by jcsteh** [comment]
Realtek(R) Audio
Driver Date: 25/10/2022
Driver Version: 6.0.9430.1
Note that I'm still using my USB-C audio adapter for other reasons, so it's slightly possible I'm wrong and it's not fixed. However, before, unless I explicitly disabled the Waves and RealTek services, even switching to speakers for a short while (which I still do sometimes) would eventually result in memory issues. I don't see that any more with the Waves and RealTek services fully enabled and occasional usage of the speakers.

**Comment by jcsteh** [comment]
This will probably fix #10185 and #11061. The nvwave WinMM code uses the completion of the last chunk for indexing, which causes buffer underruns when indexes are close together. In contrast, the WASAPI code doesn't wait for each chunk to finish. Instead, it waits until half the buffer is available. For indexing, it uses the audio playback clock rather than any completion events.

**Comment by CyrilleB79** [comment]
Reopening since WASAPI is not enabled by default anymore (#15172).
