### ISSUE TITLE
Manual attempts to update NVDA, or NVDA Add-Ons, is throwing error messages

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#12894]
### Steps to reproduce:
A) Hit NVDA + N, T, and navigate to the Check for add-on updates option
OR
B) HIT NVDA + N, H, and navigate to Check for update. . . option

### Actual behavior:
A) Receive message, "Error checking for Update."
B) Receive message, "Error checking for Add-On Updates."

### Expected behavior:
Were updates to be available, they should download and install.  If they are not present, a message indicating this, rather than an error message, should be presented

#### NVDA installed/portable/running from source:
NVDA Installed

#### NVDA version:
2021.2

#### Windows version:
Windows 10, Version 21H1, Build 19043.1237

#### Name and version of other software in use when reproducing the issue:
Not applicable

#### Other information about your system:
HP Laptop, i7 processor - 4th generation, 16 GB RAM, 1 TB SSD

#### Does the issue still occur after restarting your computer?
Yes

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes, for check for NVDA update itself.  Of course, if add-ons are disabled it's impossible to test Add-On Updater functionality.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment]
Hi, possibly related to expiration of a Lets Encrypt root certificate on September 30, 2021 as I’ve encountered this issue on some of my systems. One workaround is visiting NV Access website on preferred web browser (if using Firefox, it won’t have any impact because FF ships with its own certificates store). I have informed add-ons community to confirm if the problem is widespread (so far, we can’t really establish patterns based on reports coming from users). Thanks.

**Comment by britechguy** [comment]
No matter what it happens to be related to, something's got to be fixed.  And that something may not actually lie with NVDA itself.

It's great to have a workaround, but at the moment this is not a pressing issue for me.  I created this issue because of the flurry of reports regarding this on the NVDA Group topic, [addon updater](https://nvda.groups.io/g/nvda/topic/85979129), which gives a clear indication that this is not an isolated incident.  And you can't track an issue without an issue to track it with.

Just say your note on said topic.  I hope that others will add comments here so that some pattern may be established that allows the root cause to be determined.

**Comment by lukaszgo1** [comment]
@britechguy  Assuming this is reproducible on your machine would you be able to test with latest Alpha? The reason I ask for this is because I've fixed some issues related to the way in which NVDA fetches certificates when checking for updates in #12729 but none of my systems exhibits these symptoms so I cannot test myself. Also assuming this would not be fixed by latest Alpha could you please try checking for update and when it fails post a log - the error message from GUI alone is not enough to work further on this.

**Comment by britechguy** [comment]
Lukasz,

I literally just rebooted my machine again, and was about to fire up NVDA with debug logging enabled to attach a log for the Add-On Update, which I've now done.  I also did this again after restarting NVDA for the Update to NVDA itself error.  Both logs are attached.

I can certainly test with an alpha if that is necessary.

[Log_For_Add-Ons_Update_Failure.txt](https://github.com/nvaccess/nvda/files/7268713/Log_For_Add-Ons_Update_Failure.txt)
y
[Log_For_NVDA_Update_Failure.txt](https://github.com/nvaccess/nvda/files/7268716/Log_For_NVDA_Update_Failure.txt)
.

**Comment by lukaszgo1** [comment]
> 
> I can certainly test with an alpha if that is necessary.


Please do, since the errors in the log are identical to what I've fixed in Alpha in August.

**Comment by josephsl** [comment]
Hi, the common thread from these two logs is the SSL error that says “certificate has expired”. This lends credence to the possibility of the effect of Let’s Encrypt root certification expiration. I’m curious to know if this error is shown for others using NVDA 2021.2. Please do try with latest alpha snapshot and see if that makes a difference. Thanks.

**Comment by britechguy** [comment]
Please give me the download link for the exact alpha executable you want me to use.  I can install and try this in very short order.

**Comment by lukaszgo1** [comment]
The latest Alpha can be downloaded from [here](https://ci.appveyor.com/api/buildjobs/ro759q35w6rp6xph/artifacts/output/nvda_snapshot_alpha-23852,df92ef66.exe)

**Comment by britechguy** [comment]
Alpha is successful both in updating add-ons and NVDA, at least insofar as not giving an error message.  I get the expected "no updates available" message in both instances.  Logs are attached
[Update_Add-Ons_Success_Log.txt](https://github.com/nvaccess/nvda/files/7268977/Update_Add-Ons_Success_Log.txt)
[Update_NVDA_Success_Log.txt](https://github.com/nvaccess/nvda/files/7268978/Update_NVDA_Success_Log.txt)

.

**Comment by lukaszgo1** [comment]
Thanks. The way in which these certificates are fetched means that your stable version should now be able to check for updates too. Can you confirm?

**Comment by josephsl** [comment]
Hi, indeed Lukasz is correct: Python 3 changed SSL certificate error structure, therefore one must update Windows root certificates manually (from Python Console, type “import updateCheck; updateCheck._updateWindowsRootCertificates()” without quotes). Since Add-on Updater is also impacted, I’ll release version 21.10 of this add-on as soon as possible (that version will be a manual install). Thanks.

**Comment by britechguy** [comment]
I'll have to do that later, as I always do an "install over" with the alphas.

This leads to a question, when I am asked to do this should I actually do an "install over install" with the alpha, or just use the continue running option when I fire up the installer, but that doesn't actually install that software?

It always seems to me that the latter option is much more like using a portable version than an installed version, and for testing I try to match my "native state," which is pretty much always installed, with the very rarest of exceptions.  But if that's not necessary, then it makes that quick and dirty testing much easier to accomplish.

I presume, though, that when I reinstall 2021.2 I'll go back to it's former state of not fetching these updates correctly since I'd presume it would be a completely clean reinstall, wiping out whatever the alpha had done during its install.

**Comment by lukaszgo1** [comment]
> This leads to a question, when I am asked to do this should I actually do an "install over install" with the alpha, or just use the continue running option when I fire up the installer, but that doesn't actually install that software?
> 
> It always seems to me that the latter option is much more like using a portable version than an installed version, and for testing I try to match my "native state," which is pretty much always installed, with the very rarest of exceptions. But if that's not necessary, then it makes that quick and dirty testing much easier to accomplish.

This depends on what tests you perform and there is no good answer for all the cases? For this issue it would be certainly sufficient to use from the launcher i.e. by choosing 'continue running'.

> 
> I presume, though, that when I reinstall 2021.2 I'll go back to it's former state of not fetching these updates correctly since I'd presume it would be a completely clean reinstall, wiping out whatever the alpha had done during its install.


I don't thing so, since we're not fetching the new certificate just for NVDA but for the entire system and it ends in the global certificate store, but it needs to be tested to be certain.

**Comment by josephsl** [comment]
Hi, I would say that, for this instance, a portable copy of alpha would suffice as it will update root certificates if needed. The Python Console workaround is slightly more general but one must follow exact instructions. Thanks.

**Comment by britechguy** [comment]
Lukasz wrote, in part, "This depends on what tests you perform and there is no good answer for all the cases."

Then might I kindly suggest that you point your desired tester in the proper direction for the issue at hand?  This is not a big deal, as I could easily have done either thing, but we who are testing don't have the inside information to make an informed decision regarding how to proceed.

Just a "install this alpha version then test" versus a "you can run the alpha straight out of the installer without installing using the continue running option" would ensure you get precisely what you need.  Or more precisely it tells us how to get what you need.

I'm glad that this issue is now resolved, at least as far as knowing root causes and that a solution is in the pipeline and that there is a complete workaround until it arrives for existing users.

**Comment by mazen428** [comment]
Hello, here's another workaround that is easier and a lot user-friendly. Just install the addon, ignore the error, it's only there so 
nvda doesn't keep it installed and the issue should be fixed. On how it works, I call _updateWindowsRootCertificates in the installTasks and raise an exception so nvda removes the addon, not really the best but it works, tested it on a windows sandbox and before i installed the addon, I was getting the error. Hope this helps someone.
[NvdaCertPatch.zip](https://github.com/nvaccess/nvda/files/7269883/NvdaCertPatch.zip)

**Comment by XLTechie** [comment]
Can someone post a status update here? It seemed from the comments to be effectively resolved by #12729, but then @feerrenrut  pinned it, so evidently it's still a problem someone is trying to do something with; although what that is does not seem obvious.

**Comment by feerrenrut** [comment]
Yes, this is resolved as of #12729 and included in the 2021.3 release. I pinned this issue since it was likely to affect many users, I wanted it to be easy to find. There may still be users who have yet to update, who will need to manually download and install a fixed release (2021.3 or later).

I'll close this now.
