### ISSUE TITLE
Performance degradation in VS Code after NVDA 2022.2.4

### ISSUE THREAD

**Issue by brunoprietog** [nvaccess/nvda#14446]
### Steps to reproduce:

1. Browse to a file in Windows Explorer and open it with VS Code. Alternatively, open VS Code from the desktop or start menu shortcut.
2. Once VS Code opens, while it is loading, press up arrow and down arrow.
3. Once loaded, if you opened a file, the editor should come into focus.

### Actual behavior:

If you opened a project and press up or down arrow, NVDA reads blank all the time. It is in browse mode, outside the container that has the application role. If you opened a file, NVDA reads lines fine, but with lower performance.

You need to restart NVDA every time you open VS Code to get the performance you had before 2022.3.

This does not happen with VS Code Insiders, only with VS Code stable.

### Expected behavior:

NVDA should automatically enter the container with the application role, without being in browse mode. I imagine there is something beyond that, but in NVDA 2022.2 it worked fine and I didn't have to restart it every time I opened VS Code.

#### NVDA installed/portable/running from source:

Installed and portable

#### NVDA version:

NVDA 2022.3.2

#### Windows version:

Windows 11 22H2 (x64) build 22621.900

#### Name and version of other software in use when reproducing the issue:

VS Code 1.74.1

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Works fine in NVDA 2022.2.4. From NVDA 2022.3 onwards this problem started.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by cary-rowen** [comment]
Yes, I was able to reproduce this too, after restarting NVDA, the performance improved significantly.

**Comment by seanbudd** [comment]
Can you confirm that 2022.2.4 has this problem with the latest version of VS Code, while 2022.3.2 has issues? Considering that insiders works, it seems like it could be a VS Code issue.

**Comment by cary-rowen** [comment]
Restarting nvda while system focus is on VSCode encounters the following error.
```
ERROR - eventHandler.executeEvent (22:23:05.755) - MainThread (16040):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x060F1AD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 247, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1197, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1094, in reportFocus
  File "speech\speech.pyc", line 609, in speakObject
  File "speech\speech.pyc", line 663, in getObjectSpeech
  File "documentBase.pyc", line 74, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 110, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 235, in _findContentDescendant
LookupError: Object has no text descendants
```

**Comment by brunoprietog** [comment]
I tested the same version of VS Code (1.74.1) with the 2 versions of NVDA. With NVDA 2022.2.4 it works fine, with NVDA 2022.3.2 the problem exists. There is no change of VS Code version, only NVDA. Also, as I said, Code Insiders works fine. Thanks

**Comment by brunoprietog** [comment]
It seems that #13851  is the cause of this. In the advanced settings of NVDA, if I disable "Load Chromium virtual buffer when document busy", the problem is solved.

What I don't understand is why it works fine in VS Code Insiders and not in VS Code. As I mentioned before, the problem started from NVDA 2022.3, no matter what version of VS Code I use, unless it is VS Code Insiders where there is no problem.

**Comment by seanbudd** [comment]
@brunoprietog can you test this build, generated from #14484?
https://ci.appveyor.com/api/buildjobs/fj3233erwjy71ey7/artifacts/output%2Fnvda_snapshot_try-makeAppModuleAliasesCaseInsens-27385%2Cc91f7343.exe
I believe it should fix the issue

**Comment by cary-rowen** [comment]
Hi, @seanbudd 
I tested this build and it works fine to fix the issue.

**Comment by cary-rowen** [comment]
@seanbudd 
Should restarting NVDA in VS Code throw an error, should a separate Issue be created to deal with it? Can you reproduce the situation I have described.
Note that for the situation I described, you should press NVDA+Q and choose to restart NVDA in the ensuing dialog instead of ctrl+Alt+N which will reset the focus to the taskbar.

**Comment by brunoprietog** [comment]
Hi @seanbudd! Thanks for trying to solve the problem. Unfortunately I can still reproduce it with this build.

The way I usually open VS Code is from a terminal, WSL for example, going to a folder where I have a project and running "`code .`". When I do that, VS Code opens in the project folder, but NVDA is still in browse mode and outside the container that has the application role. You can check this by pressing down arrow repeatedly, NVDA says blank, and it should not say nothing, as it did before NVDA 2022.3, or as it does currently in VS Code Insiders. If I manually enter the container with tab or enter, and go to the file explorer, for example, when expanding a folder NVDA gets stuck for a second or so. There is also worse performance when reading indentation when editing files.

If I restart NVDA these problems go away, until I open another VS Code window.

The other way to fix it temporarily is to disable the Chromium virtual buffer setting from the NVDA advanced settings, or using VS Code Insiders.

This makes sense for me, because this feature was enabled in NVDA 2022.3. I think that's where the problem lies. It might be worth investigating why it happens in VS Code and not in VS Code Insiders.

Sorry, I don't have more knowledge to contribute, I hope it helps to solve this issue

Thanks!

**Comment by seanbudd** [comment]
@brunoprietog 
I cannot reproduce the problem you describe when using the try build I linked.

Did you restart your device after installing the try build?
When you are using VS Code, is "Screen Reader Optimized" mode enabled? (`ctrl+p`, `>`, `"Screen Reader"`)

Can you share a log file of you reproducing the issue with the try build?
- Instructions on sharing a log file: https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps#log-files-and-crash-dumps
- Please include pressing `NVDA+f1` on a VS Code window that is not working correctly, and `NVDA+f1` on a VS code window this is working correctly.

The information you provided was helpful in generating a lead to understanding the problem.
The code relating to the Chromium Virtual Buffer should not be applied to VS Code windows.
On alpha, I believe NVDA is failing to detect the VS Code window due to Microsoft renaming the exe file to `Code` with a capital `C`. That is why insiders works fine, NVDA correctly detects VS code in this case.

Would you be able to confirm the name of the `.exe` in your VS Code installation?
It should be located in `%LocalAppData%\Programs\Microsoft VS Code`

**Comment by seanbudd** [comment]
@cary-rowen If that issue can be reproduced with alpha and the try build can you please open a separate issue.

**Comment by brunoprietog** [comment]
@seanbudd yes, I restarted the computer after installing the test build and VS Code is configured to be used with screen readers, both VS Code and VS Code Insiders, in fact, they are the same settings because they are synchronized in the cloud.

I was able to reproduce the problem with the test build.

I send several logs:

1. The error is reproduced in VS Code, Load Chromium virtual buffer when document busy default (enabled). Log: [Log VS Code wrong Chromium virtual buffer enabled.txt](https://github.com/nvaccess/nvda/files/10323126/Log.VS.Code.wrong.Chromium.virtual.buffer.enabled.txt)
2. The error is reproduced on VS Code Insiders, Load Chromium virtual buffer when document busy default (enabled). Log: [Log VS Code Insiders wrong Chromium virtual buffer enabled.txt](https://github.com/nvaccess/nvda/files/10323133/Log.VS.Code.Insiders.wrong.Chromium.virtual.buffer.enabled.txt)
3. The error is not reproduced in VS Code, Load Chromium virtual buffer when document busy disabled. Log: [Log VS Code good Chromium virtual buffer disabled.txt](https://github.com/nvaccess/nvda/files/10323136/Log.VS.Code.good.Chromium.virtual.buffer.disabled.txt)
4. The error is not reproduced in VS Code Insiders, Load Chromium virtual buffer when document busy disabled. Log: [Log VS Code Insiders good Chromium virtual buffer disabled.txt](https://github.com/nvaccess/nvda/files/10323139/Log.VS.Code.Insiders.good.Chromium.virtual.buffer.disabled.txt)
5. The error is not reproduced in VS Code, Load Chromium virtual buffer when document busy default (enabled). Log: [Log VS Code Insiders good Chromium virtual buffer enabled.txt](https://github.com/nvaccess/nvda/files/10323142/Log.VS.Code.Insiders.good.Chromium.virtual.buffer.enabled.txt)

I was only able to reproduce point 2 once. All other points I was able to reproduce several times consistently.

The names of the VS Code and VS Code Insiders executables are "Code.exe" and "Code - Insiders.exe".

Thanks

**Comment by Adriani90** [comment]
@brunoprietog could you please test with the last alpha version of NVDA and the last version of VS Code? Do you still have the performance issues?

You can download the last alpha of NVDA here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by brunoprietog** [comment]
Yes, I can reproduce it with the latest NVDA alpha and the latest version of VS Code 1.76.2, although I can only reproduce it the first time I open VS Code after turning on the PC, even if I close all VS Code windows, the following times I can't reproduce it. The following times it works fine, until I restart it again

**Comment by brunoprietog** [comment]
I haven't been able to reproduce this again for a while. Maybe it has been fixed on the VS Code side. I'll close for now
