### ISSUE TITLE
Tab control in Dropbox Preferences dialog inaccessible

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1508]
**Reported by KevanGC on 2011-05-17 06:17**
You might know what Dropbox is already. It's a file host where you can upload files and share them. The Dropbox client is very accessible, but not in an important area, the Dropbox Preferences dialog.

STR:
1: Make sure Dropbox is running.
2: Go into the system tray, right-click the Dropbox icon, and open preferences.
3: Arrow around. You'll find the screen pretty much accessible, however there are multiple other screens you won't be able to switch to, because the "buttonPanel" Dropbox uses to switch tabs is not accessible to NVDA.

You can switch to these screens by moving around inside the buttonPanel with the mouse and clicking, however this is difficult because NVDA gives no feedback about the buttonPanel, other than it's a buttonPanel.

Can you get NVDA working with it? Or is it Dropbox's fault? If it is, I can try contacting Dropbox and asking them to fix it.

Thanks

**Comment by dkager** [comment]
In Dropbox 29.4.20 the tab controls are operable, but NVDA doesn't follow the focus when it moves onto the tabs bar.

**Comment by jcsteh** [comment]
I did some brief investigation. Dropbox doesn't fire a focus event (or any other event for that matter) on the tab control when it gains focus; e.g. when you tab to it. However, it does fire a stateChange event on the control that just lost focus. Also, activeChild on the dialog does return the tab control. So, it should be possible to come up with an app module that works around this. Of course, it'd be better to get this addressed in Dropbox and/or Qt5.

P3 because Dropbox is quite commonly used. There is a workaround (press left/right arrow once you tab and get nothing), but this is very hard to discover.

**Comment by Adriani90** [comment]
This issue is fixed in Dropbox 73.4.118. Closing as works for me. If you are still seeing this issue in Dropbox 73.4.118 or newer versions, please comment on this to reopen the discussion or create a new issue accordingly. Thanks.

**Comment by Brian1Gaff** [comment]
Hi  two things on this one. Firstly since one of my computers had to have 
windows 7 installed again Dropbox preferences now work pretty well again, 
Secondly, the add on does still work to make it less confusing.

I still do not know what uninstalling Avast did to the dropbox tabs etc in 
windows 7. I still have one machine with the issue, so it might be something 
that can be added to the  repair tool if we could figure out what it was!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
Did you try to run the com registry fixing tool?

You have to make sure that dropbox 73.4.118 is the version on the machine you mentioned. I don’t know exactly what Avast would influence in this matter, but I don’t think this is really caused by uninstaling Avast. Try to clean your registry with CCleaner after uninstalling Avast maybe there are some unneeded keys there.

 

 

Von: Brian Gaff <notifications@github.com> 
Gesendet: Samstag, 1. Juni 2019 19:19
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Tab control in Dropbox Preferences dialog inaccessible (#1508)

 

Hi two things on this one. Firstly since one of my computers had to have 
windows 7 installed again Dropbox preferences now work pretty well again, 
Secondly, the add on does still work to make it less confusing.

I still do not know what uninstalling Avast did to the dropbox tabs etc in 
windows 7. I still have one machine with the issue, so it might be something 
that can be added to the repair tool if we could figure out what it was!
Brian

bglists@blueyonder.co.uk <mailto:bglists@blueyonder.co.uk> 
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk <mailto:briang1@blueyonder.co.uk> , putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
