### ISSUE TITLE
NVDA 24.1b7 not working with BAUM braille displays properly

### ISSUE THREAD

**Issue by YetiAnt** [nvaccess/nvda#16212]
i have a 

   BAUM SuperVario2-64

connected via USB. It works with NVDA 2024.1B7 but the control buttons and cursor routing do not work. 
Not even when starting without add-ons and after restarting the computer.  If I start a previously saved portable version - e.g. 23.3.3 - everything works as desired.
Including the D-Keys and cursor routing.
 
The crucial lines from the logbook are probably the following:
---
INFO - brailleInput.initialize (18:26:14.706) - MainThread (9420):
Braille input initialized
INFO - braille.initialize (18:26:14.706) - MainThread (9420):
Using liblouis version 3.28.0
INFO - braille.initialize (18:26:14.706) - MainThread (9420):
Using pySerial version 3.5
INFO - braille.BrailleHandler._setDisplay (18:26:14.712) - MainThread (9420):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUGWARNING - hwPortUtils.listUsbDevices (18:26:14.713) - ThreadPoolExecutor-0_0 (7056):
Couldn't get DEVPKEY_Device_BusReportedDeviceDesc for {'hardwareID': 'USB\\VID_0A12&PID_0001&REV_8891', 'usbID': 'VID_0A12&PID_0001', 'devicePath': '\\\\?\\usb#vid_0a12&pid_0001#6&229efb56&0&14#{a5dcbf10-6530-11d2-901f-00c04fb951ed}'}: [WinError 1168] Element nicht gefunden.
DEBUGWARNING - hwPortUtils.listUsbDevices (18:26:14.714) - ThreadPoolExecutor-0_0 (7056):
Couldn't get DEVPKEY_Device_BusReportedDeviceDesc for {'hardwareID': 'USB\\VID_046D&PID_0825&REV_0012', 'usbID': 'VID_046D&PID_0825', 'devicePath': '\\\\?\\usb#vid_046d&pid_0825#104fc6a0#{a5dcbf10-6530-11d2-901f-00c04fb951ed}'}: [WinError 1168] Element nicht gefunden.
INFO - brailleDisplayDrivers.baum.BrailleDisplayDriver.__init__ (18:26:14.863) - ThreadPoolExecutor-0_0 (7056):
Found Baum SVario-64 connected via serial (COM3)
INFO - braille.BrailleHandler._setDisplay (18:26:14.869) - ThreadPoolExecutor-0_0 (7056):
Loaded braille display driver 'baum', current display has 64 cells. 
...
ERROR - hwIo.base.IoBase._notifyReceive (18:26:23.338) - hwIo.ioThread.IoThread (8048):
Traceback (most recent call last):
  File "hwIo\base.pyc", line 204, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyc", line 244, in _onReceive
  File "brailleDisplayDrivers\baum.pyc", line 264, in _handleResponse
  File "brailleDisplayDrivers\baum.pyc", line 354, in __init__
AssertionError
ERROR - hwIo.base.IoBase._notifyReceive (18:26:25.241) - hwIo.ioThread.IoThread (8048):
Traceback (most recent call last):
  File "hwIo\base.pyc", line 204, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyc", line 244, in _onReceive
  File "brailleDisplayDrivers\baum.pyc", line 264, in _handleResponse
  File "brailleDisplayDrivers\baum.pyc", line 354, in __init__

---
The complete logbook is saved in case it is needed.

**Comment by lukaszgo1** [comment]
This is an interesting one.
The failing assertion was always  there, but since #15544 assertions cause exceptions in release builds (it looks like we have no Alpha users using BAUM SuperVario2-64, that is why the issue remained undetected for so long). This assertion was introduced in #7517 which relied on an assumption that names of Braille display models cannot contain  characters other than letters and numbers. This is  clearly not the case for the display in question, as its identifier is `Baum SVario-64`. We probably should remove assertion for the Baum driver, and make our mode identifier regex less strict, so that it accepts dashes and underscores (while we don't know about any models whose identifiers contain the latter I see no reason to disallow them). cc @LeonarddeR

**Comment by seanbudd** [comment]
the assertion will no longer throw an error after #16215 is merged, however this logic should probably be fixed up still

**Comment by YetiAnt** [comment]
I just installed NVDA 2024.1B11 and the issue is fixed for my needs:
Cursorrouting and navigation keys of my SuperVario2-64 work again.

**Comment by Adriani90** [comment]
Thanks for the update, closing as works for me.

**Comment by seanbudd** [comment]
Please keep open, while this is fixed in release builds, the assertions still need fixing as this would be broken when running from source

**Comment by Adriani90** [comment]
Closing as fixed some versions of NVDA ago.

**Comment by CyrilleB79** [comment]
@Adriani90 wrote:
> Closing as fixed some versions of NVDA ago.

What are you referring to when writing so? If you are referring to https://github.com/nvaccess/nvda/issues/16212#issuecomment-1976469410, that's not correct as explained in https://github.com/nvaccess/nvda/issues/16212#issuecomment-1977462863, i.e. the bug is not fixed when running from source. If you are referring to something else, please be more specific. Thanks.

**Comment by Adriani90** [comment]
It is fixed according to my testing, also when running from source.Von meinem iPhone gesendetAm 04.10.2024 um 13:27 schrieb Cyrille Bougot ***@***.***>:﻿
@Adriani90 wrote:

Closing as fixed some versions of NVDA ago.

What are you referring to when writing so? If you are referring to #16212 (comment), that's not correct as explained in #16212 (comment), i.e. the bug is not fixed when running from source. If you are referring to something else, please be more specific. Thanks.

**Comment by CyrilleB79** [comment]
@Adriani90, sorry, just to confirm because it's not very clear to me what could have fixed this:
* Which braille display have you tested with? With a BAUM braille display (which one) or any other one?
* Since you write "some versions of NVDA ago", have you an idée how/when it was fixed (PR, NVDA version)? Or is it just because you are using such config regularly from source without any error?

Thanks.

**Comment by Adriani90** [comment]
Baum vario ultra 40.No idea what fixed this but I use it regularly with nvda from source.If the initial author or anyone else has this issue still, please comment and we can reopen.Von meinem iPhone gesendetAm 04.10.2024 um 14:11 schrieb Cyrille Bougot ***@***.***>:﻿
@Adriani90, sorry, just to confirm because it's not very clear to me what could have fixed this:

Which braille display have you tested with? With a BAUM braille display (which one) or any other one?
Since you write "some versions of NVDA ago", have you an idée how/when it was fixed (PR, NVDA version)? Or is it just because you are using such config regularly from source without any error?

Thanks.

**Comment by CyrilleB79** [comment]
@Adriani90 looking at Baum's driver, it's clear that the issue is not fixed.

Your display's name is "Baum vario ultra 40", whereas @YetiAnt's one is "BAUM SuperVario2-64". As explained in https://github.com/nvaccess/nvda/issues/16212#issuecomment-1960062895, the issue is caused by the presence of a dash character in the display model name.

The model name of your display has no dash in it so you probably have never had this exact issue, or have you?

Thus this issue needs to be reopened.
