### ISSUE TITLE
NVDA Highlighter Window gets stuck on Windows taskbar after Windows Explorer is restarted

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [nvaccess/nvda#17696]
### Steps to reproduce:
1. Enable highlighting options on NVDA --> Settings --> Vision section.
2. Restart Windows File Explorer process.

### Actual behavior:

An empty and non-responsive NVDA Highlighter Window gets stuck on the taskbar.
### Expected behavior:

There isn’t such a useless and non-closable window on the taskbar.
### NVDA logs, crash dumps and other attachments:

[nvda.log](https://github.com/user-attachments/files/18783371/nvda.log)

#### NVDA version:
2024.4.2
#### Windows version:
Windows 11 24h2
#### Name and version of other software in use when reproducing the issue:
Windows File Explorer (native)
#### Other information about your system:
I think that it is a possible cause for the following issue:

https://nvda.groups.io/g/nvda/topic/what_is_the_nvda_highlighter/105176434

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes: 2024.4, 2024.4.1. Same behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
How do you restart Windows File Explorer process?

Also, could you provide a log in debug mode.

For now, I cannot reproduce on my end but I am on Windows 10, what may make a difference.

**Comment by DimitrisKalaboukas** [comment]
@CyrilleB79 By right-clicking "explorer.exe" process in Task Manager and selecting "Restart".

[nvda.log](https://github.com/user-attachments/files/18785736/nvda.log)

**Comment by CyrilleB79** [comment]
@DimitrisKalaboukas, thanks for the second log. I have not yet looked at it.

Anyway, I have done an attempt to fix the issue.
Would you mind test [this build](Quoi qu'il en soit, j'ai fait une tentative de résoudre le problème.) to check if the issue is still present or not, and if the highlighter still works as expected?

**Comment by CyrilleB79** [comment]
@DimitrisKalaboukas, I have fixed the error in the previous message regarding the download link of the build. Could you test [this build](https://ci.appveyor.com/api/buildjobs/n9emjjcehjn72wwv/artifacts/output%2Fnvda_snapshot_pr17698-35295%2C67d9c4fc.exe)?

**Comment by DimitrisKalaboukas** [comment]
@CyrilleB79 I don’t want to risk installing an unstable version on my system. I will test it when a stable version is released and provide feedback on this thread.

**Comment by CyrilleB79** [comment]
@DimitrisKalaboukas you do not need to install this build. Just launch this installer, check the "I agree" checkbox to accept the licence and press "Continue running". NVDA will continue running from the installer, as a temporary portable copy, without touching your installed version or your configuration.
You can test the fix, and when you're done, just press `control+alt+N` to restart your normal installed NVDA copy.

Note that I am not able myself to reproduce the issue you are experimenting, maybe because I am on Windows 10. Thus, until you or someone else can test the fix, I prefer not to ask the fix to be merged in a release.

**Comment by DimitrisKalaboukas** [comment]
@CyrilleB79 Unfortunately, it doesn't fix the issue on my end.

**Comment by CyrilleB79** [comment]
@DimitrisKalaboukas thanks for having tested. Could you provide again a log while reproducing the issue? Thanks.

**Comment by DimitrisKalaboukas** [comment]
@CyrilleB79 See line 1849 (“application explorer closed”) and so on in the above debug log: https://github.com/nvaccess/nvda/issues/17696#issuecomment-2656885319

**Comment by CyrilleB79** [comment]
@DimitrisKalaboukas, sorry I have not been clear in my previous comment.

I'd like to provide a new log with the [test build](https://ci.appveyor.com/api/buildjobs/n9emjjcehjn72wwv/artifacts/output%2Fnvda_snapshot_pr17698-35295%2C67d9c4fc.exe) I have referenced in [my previous comment](https://github.com/nvaccess/nvda/issues/17696#issuecomment-2664807338).

I expect the error not to be the same as the one that was logged in your first log and I'd like to see it.

**Comment by DimitrisKalaboukas** [comment]
@CyrilleB79 

[nvda.log](https://github.com/user-attachments/files/18864781/nvda.log)

**Comment by CyrilleB79** [comment]
Thanks @hwf1324 and @DimitrisKalaboukas for the logs.

Unfortunately, I am not able to see anything that could help me find the cause of what you describe.

Maybe anyone else can reproduce and investigate?

**Comment by DimitrisKalaboukas** [comment]
@hwf1324 Well done! It fixes the issue.
