### ISSUE TITLE
Adobe crashes when NVDA highlighter is enabled

### ISSUE THREAD

**Issue by Neluser** [nvaccess/nvda#17834]
### Steps to reproduce:
You need to go to one of the links in the document
### Actual behavior:
When I'm listening to a document and when I switch reading to a link, adob acrobat crashes. Only deleting the link helps to fix the situation.
(When reading with other tools the problem is absent)

### Expected behavior:

When you click on a link, the link should read and go to the next text set by tags.

### NVDA logs, crash dumps and other attachments:

NVDA logs
```
INFO - __main__ (11:22:30.272) - MainThread (22776):
Starting NVDA version 2024.4.2 x86
INFO - core.main (11:22:30.645) - MainThread (22776):
Config dir: C:\Users\Roman\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (11:22:30.657) - MainThread (22776):
Loading config: C:\Users\Roman\AppData\Roaming\nvda\nvda.ini
INFO - core.main (11:22:33.662) - MainThread (22776):
Windows version: Windows 10 22H2 (10.0.19045) workstation AMD64
INFO - core.main (11:22:33.662) - MainThread (22776):
Using Python version 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:00:00) [MSC v.1938 32 bit (Intel)]
INFO - core.main (11:22:33.662) - MainThread (22776):
Using comtypes version 1.2.0
INFO - core.main (11:22:33.675) - MainThread (22776):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - NVDAHelperLocal (11:22:34.040) - MainThread (22776):
Thread 22776, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_initialize, 215:
ocSpeech_initialize

INFO - NVDAHelperLocal (11:22:34.041) - MainThread (22776):
Thread 22776, build\x86\localWin10\oneCoreSpeech.cpp, OcSpeechState::activate, 89:
Activating

INFO - NVDAHelperLocal (11:22:34.292) - MainThread (22776):
Thread 22776, build\x86\localWin10\oneCoreSpeech.cpp, preventEndUtteranceSilence_, 443:
AppendedSilence supported

INFO - synthDriverHandler.setSynth (11:22:34.507) - MainThread (22776):
Loaded synthDriver oneCore
WARNING - mathPres.initialize (11:22:34.755) - MainThread (22776):
MathPlayer 4 not available
INFO - core._setUpWxApp (11:22:34.755) - MainThread (22776):
Using wx version 4.2.2a1 msw (phoenix) wxWidgets 3.2.4 with six version 1.17.0
INFO - brailleInput.initialize (11:22:34.764) - MainThread (22776):
Braille input initialized
INFO - braille.initialize (11:22:34.764) - MainThread (22776):
Using liblouis version 3.31.0
INFO - braille.initialize (11:22:34.780) - MainThread (22776):
Using pySerial version 3.5
INFO - braille.BrailleHandler._setDisplay (11:22:34.795) - MainThread (22776):
Loaded braille display driver 'noBraille', current display has 0 cells.
INFO - core.main (11:22:35.384) - MainThread (22776):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (11:22:35.738) - UIAHandler.UIAHandler.MTAThread (3056):
UIAutomation: IUIAutomation6
WARNING - gui.__getattr__ (11:22:37.178) - MainThread (22776):
Importing SettingsPanel from here is deprecated. Import SettingsPanel from gui.settingsDialogs instead. 
Stack trace:
  File "nvda.pyw", line 526, in <module>
  File "core.pyc", line 879, in main
  File "globalPluginHandler.pyc", line 31, in initialize
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Roman\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 51, in <module>
    from gui import SettingsPanel, NVDASettingsDialog, guiHelper
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "gui\__init__.pyc", line 113, in __getattr__
WARNING - gui.__getattr__ (11:22:37.179) - MainThread (22776):
Importing SettingsPanel from here is deprecated. Import SettingsPanel from gui.settingsDialogs instead. 
Stack trace:
  File "nvda.pyw", line 526, in <module>
  File "core.pyc", line 879, in main
  File "globalPluginHandler.pyc", line 31, in initialize
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Roman\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 51, in <module>
    from gui import SettingsPanel, NVDASettingsDialog, guiHelper
  File "gui\__init__.pyc", line 113, in __getattr__
INFO - core.main (11:22:37.187) - MainThread (22776):
NVDA initialized
INFO - watchdog.waitForFreezeRecovery (11:22:59.276) - watchdog (15776):
Starting freeze recovery after 5.507472499972209 seconds.
INFO - watchdog.waitForFreezeRecovery (11:22:59.377) - watchdog (15776):
Recovered from freeze after 5.608761899988167 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:09.363) - watchdog (15776):
Starting freeze recovery after 10.012585699965712 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:09.414) - watchdog (15776):
Recovered from freeze after 10.063421099970583 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:36.416) - watchdog (15776):
Starting freeze recovery after 1.0010979999788105 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:36.670) - watchdog (15776):
Recovered from freeze after 1.2548398000071757 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:37.172) - watchdog (15776):
Starting freeze recovery after 0.5001477000187151 seconds.
ERROR - scriptHandler.executeScript (11:23:44.568) - MainThread (22776):
error executing script: <bound method CursorManager.script_moveByLine_forward of <virtualBuffers.adobeAcrobat.AdobeAcrobat object at 0x05C6C990>> with gesture 'стрелка вниз'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "cursorManager.pyc", line 323, in script_moveByLine_forward
  File "cursorManager.pyc", line 152, in _caretMovementScriptHelper
  File "documentBase.pyc", line 76, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 260, in __init__
  File "textInfos\offsets.pyc", line 498, in __init__
  File "virtualBuffers\__init__.pyc", line 265, in _getSelectionOffsets
OSError: [WinError 1726] Сбой при удаленном вызове процедуры
INFO - watchdog.waitForFreezeRecovery (11:23:44.619) - watchdog (15776):
Recovered from freeze after 7.9474902000511065 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:45.081) - watchdog (15776):
Starting freeze recovery after 0.5001196999801323 seconds.
INFO - watchdog.waitForFreezeRecovery (11:23:46.903) - watchdog (15776):
Recovered from freeze after 2.321930899983272 seconds.
INFO - core.main (11:23:48.124) - MainThread (22776):
Exiting
INFO - config.ConfigManager.save (11:23:48.133) - MainThread (22776):
Base configuration saved
INFO - NVDAHelperLocal (11:23:48.213) - MainThread (22776):
Thread 22776, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_terminate, 236:
ocSpeech_terminate, token: 044D3134

INFO - NVDAHelperLocal (11:23:48.213) - MainThread (22776):
Thread 22776, build\x86\localWin10\oneCoreSpeech.cpp, OcSpeechState::terminate, 106:
Terminating

INFO - __main__ (11:23:49.624) - MainThread (22776):
NVDA exit

```
Adobe Logs

```
<?xml version="1.0"?>
<!DOCTYPE AdobeCrashReport SYSTEM "AdobeCrashReporter.dtd">
<crashreport serviceVersion="23.0.0.202412091359_9601250" clientVersion="23.0.0.202412091359_9601250" applicationName="Adobe Acrobat" applicationVersion="25.001.20432" build="0" source="Windows-Client-WER" crashType="n/a">
<time year="2025" month="3" day="17" hour="10" minute="32" second="58" timeoffset="60" timezone="ÐÐ°Ð¿Ð°Ð´Ð½Ð°Ñ ÐÐ²ÑÐ¾Ð¿Ð° (Ð·Ð¸Ð¼Ð°)" crsessionduration="1742203978"/>
<user guid="b4aa30d9-0243-40e6-94a9-052e9b1eebb1"/>
<system platform="Windows 10 Pro" osversion="10.0" osbuild="19045" applicationlanguage="en-us" userlanguage="ru-UA" oslanguage="ru-RU" ram="12163" machine="Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" model="Intel64 Family 6 Model 142 Stepping 10" cpuCount="8" cpuType="8664" cpuFreq="1800 MHz" processorArchitecture="9"/>
<gpu>
<gpuinfo availability="Running/Full Power" adapterCompatibility="Citrix Systems Inc." adapterRAM="" caption="Citrix Indirect Display Adapter" description="Citrix Indirect Display Adapter" driverDate="20190123000000.000000-000" driverVersion="12.40.44.247" videoModeDescription="Ð¦Ð²ÐµÑÐ°: 1920 x 1080 x 4294967296" pnpDeviceID="PCI&#92;VEN_5853&#38;DEV_1003&#92;1&#38;79F5D87&#38;0&#38;03" installedDisplayDrivers=""/>
<gpuinfo availability="Running/Full Power" adapterCompatibility="Intel Corporation" adapterRAM="1024 MB" caption="Intel(R) UHD Graphics 620" description="Intel(R) UHD Graphics 620" driverDate="20240813000000.000000-000" driverVersion="31.0.101.2130" videoModeDescription="Ð¦Ð²ÐµÑÐ°: 1920 x 1080 x 4294967296" pnpDeviceID="PCI&#92;VEN_8086&#38;DEV_5917&#38;SUBSYS_11931025&#38;REV_07&#92;3&#38;11583659&#38;0&#38;10" installedDisplayDrivers="igd10iumd64.dll,igd12umd64.dll,igdumdim64.dll"/>
<gpuinfo availability="Off Line" adapterCompatibility="NVIDIA" adapterRAM="2048 MB" caption="NVIDIA GeForce MX150" description="NVIDIA GeForce MX150" driverDate="20241203000000.000000-000" driverVersion="32.0.15.6636" videoModeDescription="" pnpDeviceID="PCI&#92;VEN_10DE&#38;DEV_1D10&#38;SUBSYS_119A1025&#38;REV_A1&#92;4&#38;2AD6842E&#38;0&#38;00E0" installedDisplayDrivers="nvldumdx.dll"/>
</gpu>
<crash exception="EXCEPTION_ACCESS_VIOLATION" exceptionCode="0xc0000005" instruction="0x000000005B113D45">
<backtrace crashedThread="0">
<thread index="0">
<stackStatement index="0" address="0x000000005B113D45" symbolname="ObsoleteProc"/>
<stackStatement index="1" address="0x000000005B0F9940" symbolname="ObsoleteProc"/>
<stackStatement index="2" address="0x000000005B1B39BC" symbolname="PlugInMain"/>
<stackStatement index="3" address="0x00007FFF3637A8D3" symbolname="NdrSendReceive"/>
<stackStatement index="4" address="0x00007FFF36312567" symbolname="NdrStubCall2"/>
<stackStatement index="5" address="0x00007FFF359D5C0C" symbolname="CStdStubBuffer_Invoke"/>
<stackStatement index="6" address="0x00007FFF35499760" symbolname="LoadTypeLib"/>
<stackStatement index="7" address="0x00007FFF35A3CB53" symbolname="CoGetProcessIdentifier"/>
<stackStatement index="8" address="0x00007FFF35A3C8DE" symbolname="CoGetProcessIdentifier"/>
<stackStatement index="9" address="0x00007FFF359DA086" symbolname="HSTRING_UserSize"/>
<stackStatement index="10" address="0x00007FFF359C46E3" symbolname="CoUnmarshalInterface"/>
<stackStatement index="11" address="0x00007FFF35A41D6D" symbolname="CoWaitForMultipleHandles"/>
<stackStatement index="12" address="0x00007FFF359B4586" symbolname="RoGetAgileReference"/>
<stackStatement index="13" address="0x00007FFF35A4668A" symbolname="Ordinal87"/>
<stackStatement index="14" address="0x00007FFF3449EF5C" symbolname="CallWindowProcW"/>
<stackStatement index="15" address="0x00007FFF3449E684" symbolname="DispatchMessageW"/>
<stackStatement index="16" address="0x000000005E78BB38" symbolname="DllCanUnloadNow"/>
<stackStatement index="17" address="0x000000005E78AFDC" symbolname="DllCanUnloadNow"/>
<stackStatement index="18" address="0x000000005E78AEAD" symbolname="DllCanUnloadNow"/>
<stackStatement index="19" address="0x000000005E4CCB41" symbolname="AcroWinMainSandbox"/>
<stackStatement index="20" address="0x000000005E4CA6B8" symbolname="AcroWinMainSandbox"/>
<stackStatement index="21" address="0x00007FF6E6B89C56" symbolname="CreateCoreWebview2EnvironmentSandbox"/>
<stackStatement index="22" address="0x00007FF6E6C647E2" symbolname="AcroRd32IsBrokerProcess"/>
<stackStatement index="23" address="0x00007FFF34E47374" symbolname="BaseThreadInitThunk"/>
<stackStatement index="24" address="0x00007FFF364BCC91" symbolname="RtlUserThreadStart"/>
</thread>
</backtrace>
<registerSet>
<register name="RAX" value="0x0000000000001BC3"/>
<register name="RBX" value="0x0000000000000000"/>
<register name="RCX" value="0x000000000000FFFF"/>
<register name="RDX" value="0x0000000000000001"/>
<register name="RSI" value="0x000001EF2D263570"/>
<register name="RDI" value="0x0000000000000001"/>
<register name="RSP" value="0x000000BBE4F9DD30"/>
<register name="RBP" value="0x000000BBE4F9DE50"/>
<register name="RIP" value="0x000000005B113D45"/>
<register name="EFL" value="0x0000000000010213"/>
<register name="LastExceptionToRip" value="0x0000000000000000"/>
<register name="LastExceptionFromRip" value="0x0000000000000000"/>
</registerSet>

<binaryImageSet>
<binaryImage start="0x00007FF6E6900000" end="0x00007FF6E6F10000" path="adobe\Acrobat.exe" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF36470000" end="0x00007FFF36668000" path="ntdll.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF34E30000" end="0x00007FFF34EF2000" path="kernel32.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF33B80000" end="0x00007FFF33E7F000" path="KERNELBASE.dll" version="6.2.19041.5607"/>
<binaryImage start="0x00007FFF34490000" end="0x00007FFF3462D000" path="user32.dll" version="6.2.19041.4717"/>
<binaryImage start="0x000001EF1D490000" end="0x000001EF1D4B2000" path="win32u.dll" version="6.2.19041.5607"/>
<binaryImage start="0x00007FFF357E0000" end="0x00007FFF3580B000" path="gdi32.dll" version="6.2.19041.4474"/>
<binaryImage start="0x00007FFF341F0000" end="0x00007FFF3430A000" path="gdi32full.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF33F60000" end="0x00007FFF33FFD000" path="msvcp_win.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF34340000" end="0x00007FFF34440000" path="ucrtbase.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF35CE0000" end="0x00007FFF35D8F000" path="advapi32.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF35330000" end="0x00007FFF353CE000" path="msvcrt.dll" version="7.0.19041.3636"/>
<binaryImage start="0x00007FFF356E0000" end="0x00007FFF3577F000" path="sechost.dll" version="6.2.19041.5072"/>
<binaryImage start="0x00007FFF36300000" end="0x00007FFF36423000" path="rpcrt4.dll" version="6.2.19041.4957"/>
<binaryImage start="0x000001EF1D500000" end="0x000001EF1D527000" path="bcrypt.dll" version="6.2.19041.5369"/>
<binaryImage start="0x00007FFF36280000" end="0x00007FFF362D5000" path="shlwapi.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF28A80000" end="0x00007FFF28B8A000" path="winhttp.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF333D0000" end="0x00007FFF333DC000" path="CRYPTBASE.DLL" version="6.2.19041.3636"/>
<binaryImage start="0x000001EF1D530000" end="0x000001EF1D55F000" path="imm32.dll" version="6.2.19041.4474"/>
<binaryImage start="0x00007FFF1B580000" end="0x00007FFF1B81A000" path="comctl32.dll" version="6.10.19041.4355"/>
<binaryImage start="0x00007FFF2DFB0000" end="0x00007FFF2E04E000" path="uxtheme.dll" version="6.2.19041.4529"/>
<binaryImage start="0x00007FFF35970000" end="0x00007FFF35CC5000" path="combase.dll" version="6.2.19041.5553"/>
<binaryImage start="0x000001EF1FF90000" end="0x000001EF200A5000" path="msctf.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF35490000" end="0x00007FFF3555D000" path="oleaut32.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF06370000" end="0x00007FFF06457000" path="nvdaHelperRemote.dll" version="2024.4.2.35031"/>
<binaryImage start="0x00007FFF35840000" end="0x00007FFF3596B000" path="ole32.dll" version="6.2.19041.5369"/>
<binaryImage start="0x00007FFF05AD0000" end="0x00007FFF05B36000" path="oleacc.dll" version="7.2.19041.3636"/>
<binaryImage start="0x00007FFEB48A0000" end="0x00007FFEB48B9000" path="usp10.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF29B90000" end="0x00007FFF29B9A000" path="version.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF2E670000" end="0x00007FFF2E854000" path="dbghelp.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF286B0000" end="0x00007FFF286E4000" path="dbgcore.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF34000000" end="0x00007FFF34082000" path="bcryptPrimitives.dll" version="6.2.19041.5007"/>
<binaryImage start="0x00007FFF322F0000" end="0x00007FFF32302000" path="kernel.appcore.dll" version="6.2.19041.3758"/>
<binaryImage start="0x00007FFF0DD70000" end="0x00007FFF0DE69000" path="textinputframework.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF2B870000" end="0x00007FFF2BBCB000" path="CoreUIComponents.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF353E0000" end="0x00007FFF3548D000" path="SHCore.dll" version="6.2.19041.4522"/>
<binaryImage start="0x00007FFF2BC70000" end="0x00007FFF2BD62000" path="CoreMessaging.dll" version="6.2.19041.5486"/>
<binaryImage start="0x00007FFF35670000" end="0x00007FFF356DB000" path="ws2_32.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF32D60000" end="0x00007FFF32D93000" path="ntmarta.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF2D190000" end="0x00007FFF2D2E7000" path="WinTypes.dll" version="6.2.19041.5369"/>
<binaryImage start="0x000000005DEB0000" end="0x0000000062F9B000" path="adobe\Acrobat.dll" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF346C0000" end="0x00007FFF34E2D000" path="shell32.dll" version="6.2.19041.5553"/>
<binaryImage start="0x00007FFECC9E0000" end="0x00007FFECD10A000" path="adobe\AGM.dll" version="7.1.10.1"/>
<binaryImage start="0x000001EF200B0000" end="0x000001EF20521000" path="setupapi.dll" version="6.2.19041.5369"/>
<binaryImage start="0x00007FFF34440000" end="0x00007FFF3448E000" path="cfgmgr32.dll" version="6.2.19041.3996"/>
<binaryImage start="0x00007FFEB3AA0000" end="0x00007FFEB3AC5000" path="adobe\BIB.dll" version="4.0.15.1"/>
<binaryImage start="0x00007FFECAF20000" end="0x00007FFECB364000" path="adobe\CoolType.dll" version="8.3.12.1"/>
<binaryImage start="0x00007FFF2E380000" end="0x00007FFF2E3AF000" path="dwmapi.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF20DF0000" end="0x00007FFF20E7D000" path="msvcp140.dll" version="14.40.33816.0"/>
<binaryImage start="0x00007FFF2DCE0000" end="0x00007FFF2DCE7000" path="MSVCP140_CODECVT_IDS.dll" version="14.40.33816.0"/>
<binaryImage start="0x00007FFF32EF0000" end="0x00007FFF32F2B000" path="IPHLPAPI.DLL" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF20DD0000" end="0x00007FFF20DDC000" path="secur32.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF20ED0000" end="0x00007FFF20EEE000" path="VCRUNTIME140.dll" version="14.40.33816.0"/>
<binaryImage start="0x00007FFF20EC0000" end="0x00007FFF20ECC000" path="VCRUNTIME140_1.dll" version="14.40.33816.0"/>
<binaryImage start="0x00007FFF03A10000" end="0x00007FFF03B40000" path="adobe\ACE.dll" version="6.0.11.1"/>
<binaryImage start="0x00007FFEF1770000" end="0x00007FFEF177A000" path="SensApi.dll" version="6.2.19041.1"/>
<binaryImage start="0x00007FFF339C0000" end="0x00007FFF339F2000" path="sspicli.dll" version="6.2.19041.5369"/>
<binaryImage start="0x00007FFF33010000" end="0x00007FFF3305B000" path="powrprof.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF32ED0000" end="0x00007FFF32EE2000" path="umpdc.dll"/>
<binaryImage start="0x00007FFF31B00000" end="0x00007FFF322A4000" path="windows.storage.dll" version="6.2.19041.5607"/>
<binaryImage start="0x00007FFF33460000" end="0x00007FFF3348B000" path="wldp.dll" version="6.2.19041.5553"/>
<binaryImage start="0x00007FFF33A40000" end="0x00007FFF33A65000" path="profapi.dll" version="6.2.19041.5553"/>
<binaryImage start="0x00007FFF34090000" end="0x00007FFF341EC000" path="crypt32.dll" version="6.2.19041.5072"/>
<binaryImage start="0x00007FFF06D20000" end="0x00007FFF06DCC000" path="TextShaping.dll"/>
<binaryImage start="0x000000005CAD0000" end="0x000000005DEA1000" path="adobe\AcroForm.api" version="25.1.20432.0"/>
<binaryImage start="0x000000005CA20000" end="0x000000005CAC7000" path="adobe\AXSLE.dll" version="6.0.0.52225"/>
<binaryImage start="0x00007FFEEADF0000" end="0x00007FFEEAF90000" path="adobe\DigSig.api" version="25.1.20432.0"/>
<binaryImage start="0x000000005BE50000" end="0x000000005CA18000" path="adobe\PPKLite.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF1E290000" end="0x00007FFF1E299000" path="wsock32.dll" version="6.2.19041.1"/>
<binaryImage start="0x000000005B240000" end="0x000000005BE45000" path="adobe\Annots.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF1FC90000" end="0x00007FFF1FE38000" path="GdiPlus.dll" version="6.2.19041.5369"/>
<binaryImage start="0x0000000063070000" end="0x000000006309B000" path="adobe\AXE8SharedExpat.dll" version="6.0.0.52225"/>
<binaryImage start="0x00007FFF33240000" end="0x00007FFF332AC000" path="mswsock.dll" version="6.2.19041.5553"/>
<binaryImage start="0x00007FFEF2280000" end="0x00007FFEF25CD000" path="msftedit.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF0AA60000" end="0x00007FFF0AC06000" path="Windows.Globalization.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF18DA0000" end="0x00007FFF18DFB000" path="Bcp47Langs.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF18250000" end="0x00007FFF1827D000" path="BCP47mrm.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFEF2690000" end="0x00007FFEF26B5000" path="globinputhost.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF334A0000" end="0x00007FFF334B8000" path="cryptsp.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF32B10000" end="0x00007FFF32B48000" path="rsaenh.dll" version="6.2.19041.5553"/>
<binaryImage start="0x00007FFEFCC70000" end="0x00007FFEFCDA5000" path="adobe\AdobeXMP.dll" version="9.1.1.53142"/>
<binaryImage start="0x00007FFEFF350000" end="0x00007FFEFF645000" path="UIAutomationCore.dll" version="7.2.19041.4355"/>
<binaryImage start="0x00007FFF2DB50000" end="0x00007FFF2DC46000" path="propsys.dll" version="7.0.19041.5369"/>
<binaryImage start="0x00007FFF21FC0000" end="0x00007FFF21FEB000" path="adobe\BIBUtils.dll" version="4.0.21.1"/>
<binaryImage start="0x00007FFF2C1E0000" end="0x00007FFF2C274000" path="apphelp.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF29140000" end="0x00007FFF29157000" path="NetworkExplorer.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF20EA0000" end="0x00007FFF20EBD000" path="mpr.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF05920000" end="0x00007FFF05949000" path="p9np.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF2C9E0000" end="0x00007FFF2C9EB000" path="drprov.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF327D0000" end="0x00007FFF3282B000" path="winsta.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF21960000" end="0x00007FFF2197F000" path="ntlanman.dll" version="6.2.19041.4842"/>
<binaryImage start="0x00007FFF18E90000" end="0x00007FFF18EAE000" path="davclnt.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF17A40000" end="0x00007FFF17A4D000" path="davhlpr.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFEB39F0000" end="0x00007FFEB3A9A000" path="adobe\sqlite.dll" version="24.5.20320.0"/>
<binaryImage start="0x000000005B180000" end="0x000000005B235000" path="adobe\Accessibility.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF33910000" end="0x00007FFF339B2000" path="sxs.dll" version="6.2.19041.3636"/>
<binaryImage start="0x000000005B0F0000" end="0x000000005B171000" path="adobe\PDDom.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFEFF2D0000" end="0x00007FFEFF34F000" path="OneCoreCommonProxyStub.dll" version="6.2.19041.4597"/>
<binaryImage start="0x000000005B080000" end="0x000000005B0E6000" path="adobe\PaperCapture.api" version="25.1.20432.0"/>
<binaryImage start="0x000000005A510000" end="0x000000005B074000" path="adobe\TouchUp.api" version="25.1.20432.0"/>
<binaryImage start="0x000000005A490000" end="0x000000005A501000" path="adobe\reflow.api" version="25.1.20432.0"/>
<binaryImage start="0x0000000059E00000" end="0x000000005A48F000" path="adobe\MakeAccessible.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFEB4480000" end="0x00007FFEB464C000" path="adobe\CRClient.dll" version="23.0.0.0"/>
<binaryImage start="0x00007FFF33B10000" end="0x00007FFF33B78000" path="wintrust.dll" version="6.2.19041.5553"/>
<binaryImage start="0x00007FFF336D0000" end="0x00007FFF336E2000" path="msasn1.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF27DC0000" end="0x00007FFF27DD1000" path="wbemprox.dll" version="6.2.19041.4474"/>
<binaryImage start="0x00007FFF23830000" end="0x00007FFF238C0000" path="wbemcomn.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF362E0000" end="0x00007FFF362FD000" path="imagehlp.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF196D0000" end="0x00007FFF19734000" path="Windows.FileExplorer.Common.dll" version="6.2.19041.4957"/>
<binaryImage start="0x00007FFF182C0000" end="0x00007FFF182E4000" path="edputil.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF06DD0000" end="0x00007FFF06F16000" path="Windows.StateRepositoryPS.dll" version="6.2.19041.5438"/>
<binaryImage start="0x00007FFF1BCD0000" end="0x00007FFF1BEC1000" path="urlmon.dll" version="11.0.19041.5607"/>
<binaryImage start="0x00007FFF20190000" end="0x00007FFF2044F000" path="iertutil.dll" version="11.0.19041.5607"/>
<binaryImage start="0x00007FFF20D00000" end="0x00007FFF20D28000" path="srvcli.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF33000000" end="0x00007FFF3300C000" path="netutils.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF1E6B0000" end="0x00007FFF1E6C3000" path="virtdisk.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF1E690000" end="0x00007FFF1E69B000" path="fltLib.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF067B0000" end="0x00007FFF067D2000" path="cldapi.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFEF9160000" end="0x00007FFEF91F4000" path="appresolver.dll" version="6.2.19041.4842"/>
<binaryImage start="0x00007FFF326C0000" end="0x00007FFF326E9000" path="slc.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF33A00000" end="0x00007FFF33A2E000" path="userenv.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF32690000" end="0x00007FFF326B5000" path="sppc.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF1FE40000" end="0x00007FFF2017B000" path="msi.dll" version="5.0.19041.5486"/>
<binaryImage start="0x0000000059DC0000" end="0x0000000059DF3000" path="adobe\Updater.api" version="25.1.20432.0"/>
<binaryImage start="0x0000000058720000" end="0x0000000058765000" path="adobe\IA32.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF1E9B0000" end="0x00007FFF1EE87000" path="wininet.dll" version="11.0.19041.5438"/>
<binaryImage start="0x00007FFF1B820000" end="0x00007FFF1B837000" path="ondemandconnroutehelper.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF2A270000" end="0x00007FFF2A27B000" path="winnsi.dll" version="6.2.19041.3636"/>
<binaryImage start="0x000001EF22440000" end="0x000001EF22448000" path="nsi.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF2A010000" end="0x00007FFF2A027000" path="dhcpcsvc6.DLL" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF29EC0000" end="0x00007FFF29EDD000" path="dhcpcsvc.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFEF2000000" end="0x00007FFEF2081000" path="PhotoMetadataHandler.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00007FFF2DD70000" end="0x00007FFF2DF24000" path="WindowsCodecs.dll" version="6.2.19041.5129"/>
<binaryImage start="0x00007FFF2CBD0000" end="0x00007FFF2CC7E000" path="mscms.dll" version="6.2.19041.5129"/>
<binaryImage start="0x00007FFF2C9C0000" end="0x00007FFF2C9D1000" path="ColorAdapterClient.dll" version="6.2.19041.5129"/>
<binaryImage start="0x00007FFF338A0000" end="0x00007FFF338D3000" path="devobj.dll" version="6.2.19041.4355"/>
<binaryImage start="0x00000000586C0000" end="0x000000005871F000" path="adobe\weblink.api" version="25.1.20432.0"/>
<binaryImage start="0x00007FFEC4D10000" end="0x00007FFEC50EC000" path="adobe\EScript.api" version="25.1.20432.0"/>
<binaryImage start="0x000001EF226D0000" end="0x000001EF226D8000" path="psapi.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFF25020000" end="0x00007FFF25047000" path="winmm.dll" version="6.2.19041.3636"/>
<binaryImage start="0x00007FFECDAF0000" end="0x00007FFECDDB8000" path="adobe\LogSession.dll" version="8.8.0.7"/>
<binaryImage start="0x00007FFED4280000" end="0x00007FFED444A000" path="adobe\AcroDunamis.dll" version="25.1.20432.0"/>
<binaryImage start="0x00007FFF20C80000" end="0x00007FFF20CFD000" path="adobe\AdobePIP.dll" version="8.8.0.7"/>
</binaryImageSet>
<dumpType>
Mini
</dumpType>
<hbLogSessionDllStatus>
ERROR_HB_UNABLE_TO_LOAD_DLL
</hbLogSessionDllStatus>
</crash>

<sessionId>
00000000-0000-0000-0000-000000000000
</sessionId>
<dunamisConfigGuid>
30bf5565-ab10-474a-b541-b39e24dfbe2c
</dunamisConfigGuid>
<imsUserGuid>
5F7A07AE5BB5FC140A495C80@AdobeID
</imsUserGuid>
</crashreport>


```
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
2024.4.2
#### Windows version:
Windows 10 Pro 19045.5608
#### Name and version of other software in use when reproducing the issue:
Adobe Acrobat Pro version 2025.001.20432 | 64-bit
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
There is no problem when reading with nvda 2023.3.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by SaschaCowley** [comment]
Welcome @Neluser ,

We are unable to process this issue as it stands.

- To be able to reproduce this issue, we need a sample document. Please either upload a document that exhibits this behaviour here, or email it to info@nvaccess.org and mention this issue.
- Thank you for providing a log file. Unfortunately, we need a [debug log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Please set logging level to debug in NVDA's General preferences, reproduce the issue, and upload the resultant log file.

Kind Regards,
NV Access Software Developers

**Comment by Neluser** [comment]
Good day, thanks for your reply , unfortunately I can't give a sample document as it is at a stage when it is still considered confendial .
I attach a new log.
If the new log does not help in any way, the ticket can be closed.
Thank you.

[nvda.log](https://github.com/user-attachments/files/19335430/nvda.log)

**Comment by shindere** [comment]
Hello, aren't you able to create a minimal example that you would be
able to share?

**Comment by Neluser** [comment]
Good day, I found the cause of the problem. Disabling “NVDAHighlighter” fixed the problem
I found a similar problem in another old document and the solution worked in this case as well.
I attach new logs and also send the document for testing to the mail specified in the previous message.


[Adobe log.TXT](https://github.com/user-attachments/files/19363693/Adobe.log.TXT)
[nvda.log](https://github.com/user-attachments/files/19363692/nvda.log)

**Comment by SaschaCowley** [comment]
@Neluser do you mean unchecking "Enable Highlighting" in NVDA Settings -> Vision?

**Comment by seanbudd** [comment]
This needs to be reported to Adobe and fixed by them, we need them to debug the crash dump file and let us know what is causing the crash.
Make sure to provide them a [crash dump](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour.

**Comment by Neluser** [comment]
Hi, I apologize for the long reply, I sent all the dumps and logs to adobe support yesterday, hopefully that will help fix this issue.

**Comment by seanbudd** [comment]
Update for this issue:

Given it seems adobe is not going to address this, in the mean time we encourage a PR to NVDA which does the following:

- disables NVDA highlighter while the Adobe reader app module is active to avoid the crash
- document this limitation in the user guide and include a link to report the issue to adobe

**Comment by chogenkamp** [comment]
I am still experiencing a similar bug (it's not just links but any use of the arrow keys to move between elements eventually causes a crash) and turning off Visual Highlight does seem to stop the crashing but that's not ideal as it's an excellent way to see where you are in the PDF, especially if recording your movements to show others. Is there no possible fix on NVDA's end, to amend the Visual Highlight possibly?

**Comment by seanbudd** [comment]
@chogenkamp - no, there is no possible fix. When we request information to perform the highlighting, Adobe reader crashes. Adobe Reader shouldn't crash when receiving such API calls. Please contact Adobe to request a fix.

**Comment by ktdid518** [comment]
@seanbudd Hi, Sean! I've just spent some time exploring this crash issue and am also experiencing Adobe crashing when the Visual Highlight preference is turned on and a link is interacted with. I have been using NVDA for quite some time with Visual Highlight turned off as it also causes crashes when interacting with any form elements — this is an NVDA bug confirmed by NVDA.

Crashes resulting from Visual Highlight being turned on is not only an issue for us visual testers/instructors/learners, but a critical accessibility issue for native screen reader users (low-sighted, TBI, ADHD, and more). As the NVDA bug exists for form elements, it could be possible for a new NVDA bug regarding links, yes? Is there a timeline to fix the form elements/Visual Highlight bug?

Thank you!

**Comment by seanbudd** [comment]
@ktdid518 - as mentioned several times in this thread, this is an issue with Adobe Reader. Please report it to Adobe.

**Comment by ktdid518** [comment]
@seanbudd What about the confirmed (by NVDA) NVDA bug that causes Acrobat to crash when interacting with form elements when Visual Highlight is turned on?

**Comment by seanbudd** [comment]
@ktdid518 - as mentioned previously, the crash with visual highlight is a bug with adobe. Can you please explain what you mean by confirmed by NVDA? Adobe Acrobat is crashing as a result of a normal accessibility API call. When NVDA asks Adobe for information so we can create the highlight window, Adobe Acrobat chooses to crash instead of give us this information.

**Comment by ktdid518** [comment]
@seanbudd I didn't see anyone reporting the issue regarding form elements creating the crash specifically. Apologies if I missed that when looking through.

My long-standing issue is: Acrobat to crash when interacting with form elements when Visual Highlight is turned on. 

August 25, 2025, after getting absolutely no where and no help from Adobe, I reached out directly to NVDA via email. After some back and forth, I asked if this issue would be fixed and the answer I received was: "Yes hopefully we'll get that fixed sooner rather than later."

From that point on, I have had to leave Visual Highlight off in order to test accessible PDFs. I have disabilities and would find it incredibly helpful to be able to turn Visual Highlight back on. 

The fact that this is a long-standing accessibility issue must be supremely frustrating for native users that need that visual focus and leads me to my next question:

If it's not an NVDA bug, and NVDA is very aware of this issue directly effecting the accessibility that their users rely on: has NVDA communicated with Acrobat to create a solution together? If not, can that be done? Thank you.

**Comment by seanbudd** [comment]
>If it's not an NVDA bug, and NVDA is very aware of this issue directly effecting the accessibility that their users rely on: has NVDA communicated with Acrobat to create a solution together? If not, can that be done? Thank you.

Correct, it's not an NVDA bug, and NV Access is aware of this (I am speaking on behalf of NV Access here). NV Access and many community members have reported this issue to Adobe. Please also report the issue, as it is the only way to bring further attention to it to Adobe.

**Comment by ktdid518** [comment]
@seanbudd I reported the issue last year. I tried and tried and tried with Adobe who completely dismissed responsibility/claimed it was not a bug on their end. I lost so much work time uninstalling, installing, troubleshooting, etcetera, as I'm sure many experiencing these issues have. Then, NV Access told me they were working to fix it. Hence my confusion here. I'm sure you're just as frustrated as we are by having to repeat yourself.

As you've explained that triggering the Visual Highlight on interactive elements is a normal accessibility API call from NVDA that  shouldn't crash Acrobat, I can only gather that Adobe is more concerned with their AI and collecting big monthly membership fees than accessibility and their users.

Thank you!

**Comment by seanbudd** [comment]
@ktdid518 - I'm sorry that you were misled with a message saying we were working on it. I'm not sure on the origins of this message, but it wasn't accurate. If you are still in contact with Adobe, can you ask them to provide evidence that they are handling the API call correctly, and send it to info@nvaccess.org. We particularly need details on the crash dump, as all crash information is a secret kept by Adobe. Even if NVDA wasn't handling something correctly, we need the crash information from Adobe.

**Comment by chogenkamp** [comment]
> Please also report the issue, as it is the only way to bring further attention to it to Adobe.

I think it needs to be stated how difficult it is to directly communicate with Adobe about these issues. There is no direct support email or contact form that can be used, I tried both posting in their Acrobat bug report/suggestions site on UserVoice (and got banned for accidental spamming due to the malfunction on their commenting system lol) and posting on their community forum ([see post](https://community.adobe.com/t5/acrobat-discussions/acrobat-pro-crashes-when-using-nvda-with-visual-highlight-setting-turned-on/td-p/15665964)) where I got one reply from an Adobe staff person saying they couldn't replicate the crash and asking me for more app info, which I provided and 5 days later, no new reply from that staff member. I even tried to include a copy of your comment @seanbudd about API for their records. 

The reality is that posting bug reports or posting for help on the Adobe forums only gets us so far, as just regular Adobe customers, we're a dime a dozen, easy to ignore. This ends up being a "broken telephone" situation where we are poorly playing intermediary between NVDA and Adobe, when really the best way to resolve this issue would be for NVDA and Adobe to communicate directly. Is there no direct contact between NVDA and Adobe, no one at NVDA with any sort of direct relationship with a rep at Adobe, in their accessibility department or elsewhere?

**Comment by seanbudd** [comment]
I'm not sure what to say @chogenkamp about Adobe's poor customer service here, it's very easy to reproduce this crash. Please remember that "NVDA" is the community; it's you, me and all our volunteers and users. Even when we contact them as NV Access, the organisation, their priorities and business practices are up to them. We try to to also report all serious third party issues with the developers where possible, but unfortunately software developers don't magically listen to us, they still have their own priorities. It often takes intense community pressure and lawsuits, to get software companies to comply with accessibility. These companies are often ignoring their own internal experts on accessibility, advocating for these fixes. Communication from NV Access is just a small drop in the bucket of what is needed to get these things fixed.

**Comment by CyrilleB79** [comment]
@chogenkamp in the link you've provided you write:
> And I didn't change the NVDA settings from the default install settings, which includes showing the Speech Viewer panel on start up and Visual Highlight - Enable Highlighting was turned on by default

That's not true. Visual Highlight is disabled by default in NVDA's settings and, as well, the speech viewer is not showing at NVDA startup by default. If an Adobe employee has tried to reproduce, they may just have started NVDA with its default settings, opened the document and read it, and did not succeed in reproducing.

For whoever is reproducing this issue, I have not tried myself, I'd recommend to open a brand new issue replacing this one, putting in the initial description:
* Detailed steps to reproduce
* a simple sample document where the issue can be reproduced
* updated NVDA, Windows and Acrobat versions

Now that we have understood the cause of this issue, an Adobe employee wanting to investigate this issue should not have to read all the comments to find the sample document or how to configure NVDA to reproduce, the more if Adobe is not easy to make collaborate.

**Comment by chogenkamp** [comment]
@CyrilleB79 Sorry I did a lot of different things trying to troubleshoot this issue so yes I may have gotten confused what exactly are the default settings for NVDA, I was just basing my remark on how NVDA functioned when I last uninstalled it and reinstalled it to try to fix this problem, when I opened NVDA it showed Visual Highlight and the Speech Viewer, maybe those were my changes that somehow persisted in my laptop even after I uninstalled NVDA. All the more reason for someone from NVDA more knowledgeable with the specifics of the app to work directly with Adobe, it took me literally months to figure out that the issue was in fact Visual Highlight because I am not an app developer who might have the "insider info" to better guess what is happening. I can't overstate how painfully slow it can be to try to figure out what is wrong with an app when you think you've done everything right and there's not an obvious correlation between Action A and the app crashing.

@seanbudd I appreciate what you are saying about it being easy to ignore accessibility, but really that just cements my original point that telling people to report things to Adobe doesn't seem particularly productive as it creates a false sense that a) it's easy to do so (hence why I mentioned my difficulties, Adobe pretends to encourage feedback but realistically makes it very difficult to get in touch with an actual person in a way that Adobe staff just can't ignore) and b) that realistically using the only Adobe-provided means for flagging bugs (either their wonky UserVoice site or the community forums) feels like the chance of getting Adobe staff to even notice let alone do anything, you might as well stand outside and shout your bug to the wind. If future suggestions like that were amended to "Please report it to Adobe, though typically they may not be responsive to reports" that would cover it for me, just a suggestion.

**Comment by CyrilleB79** [comment]
> [@CyrilleB79](https://github.com/CyrilleB79) Sorry I did a lot of different things trying to troubleshoot this issue so yes I may have gotten confused what exactly are the default settings for NVDA, I was just basing my remark on how NVDA functioned when I last uninstalled it and reinstalled it to try to fix this problem, when I opened NVDA it showed Visual Highlight and the Speech Viewer, maybe those were my changes that somehow persisted in my laptop even after I uninstalled NVDA.

Yes, settings are persisted when you uninstall and reinstall NVDA and you are not even offered the option to remove them, unfortunately (see #6869 and #9596).

**Comment by hwf1324** [comment]
Can this issue be reproduced in Acrobat Reader? I triggered a few crashes while testing with Acrobat Reader before, but I am unable to do so now.

I'm sorry, I don't have access to Acrobat Pro for testing.

Additionally, this issue is likely related to the virtual buffer. Have you tried disabling only the browse mode highlight?

**Comment by seanbudd** [comment]
Locking this thread as the conversation has resolved and we want to ensure the resolution doesn't get lost in further comments.

This issue is caused by NVDA trying to perform visual highlight in Adobe Reader. When we attempt this, Acrobat causes the crash. We cannot work around this or avoid this. Only Adobe can investigate and fix this.
In the mean time, avoid using visual highlight in adobe reader.
It seems adobe is not going to address this, in the mean time we encourage a PR to NVDA which does the following:

* disables NVDA highlighter while the Adobe reader app module is active to avoid the crash
* document this limitation in the user guide and include a link to report the issue to adobe
