### ISSUE TITLE
Feature request: Improve NVDA performance with sound cards

### ISSUE THREAD

**Issue by harun-342** [nvaccess/nvda#18155]
### Is your feature request related to a problem? Please explain.
NVDA is slowing down significantly on Ultrabooks due to the sound card sleeping.
### Explain your desired solution
Is there a feature that would allow NVDA to keep the sound card awake as long as NVDA is open? NVDA's ability to keep the sound cards open does not help with this issue.
### Explain your alternatives
If necessary, Microsoft should be contacted to make them aware of this issue.
### Additional context

**Comment by josephsl** [comment]
Hi, this is more of a sound card driver setting/issue, more so if the issue also happens with Narrator. If it does happen with Narrator as well, then the next step would be tweaking power management settings in the sound card driver. Thanks.

**Comment by Adriani90** [comment]
There is a hidden setting called white noise in your nvda.ini in apodata/roaming in user config. You can enable background white noise which should force your sound card to stay awake.

**Comment by harun-342** [comment]
@Adriani90
Hello, to be honest, I don't know English very well, I searched for the setting you mentioned with the translation but I couldn't find it. If you tell me exactly which line it is in the NVDA.ini file, I can find it, thank you.

**Comment by RuturajL** [comment]
@Adriani90 , would you be refering to this thing perhaps?
Press NVDA+ctrl+U to open NVDA Audio settings. Then, tab to Time to keep audio device awake after speech (seconds)  edit.
Here, perhaps set it to something like thousand, and the issue should be unnoticible.

**Comment by harun-342** [comment]
@RuturajL
If that's what's meant, then unfortunately it doesn't solve the problem. That's why I felt the need to request a new feature.

**Comment by Adriani90** [comment]
I was refering to what @wmhn1872265132 described.
So if whitenoise doesn't help, then it is really a tricky case.
Even if this was possible to solve in NVDA itself, I think the downside would be that you get less running time when on batery, especially very relevant for Laptops. So this should ideally be solved in Sound card's drivers instead of NVDA. Do you notice this issue also when changing your energy plan to best performance or so?

**Comment by ABuffEr** [comment]
Hi @harun-342,
some things you can try:
1. use [Silenzio](https://www.stefankiss.sk/files/programy/Silenzio_2.1_setup.exe) (direct link, the site is not to easy to navigate);
2. instead of increasing performance, decrease/disable the energy saving on USB or PCI Express, according to your configuration, from advanced energy settings;
3. going to device manager, search your sound card/headphones (you can find a couple of items in different categories), and open properties; then see if there are advanced options related to energy saving;
4. try these [two tweaks](https://github.com/ABuffEr/audiocaffeine) (instructions under second header of level 1).

**Comment by harun-342** [comment]
@ABuffEr
Is it possible to add the changes made in the registry to NVDA, that is, what if NVDA added these values ​​to the registry when it was installed?

**Comment by josephsl** [comment]
Hi,

Okay, some things don't add up:

* Which NVDA version did you install on this ultrabook?
* What is the Windows version you have?
* What is the speeh synthesizer you have?
* Any add-ons?

Also, does it make a difference if you try NVDA 2025.1 beta 8?

Thanks.

**Comment by harun-342** [comment]
@josephsl
I'm on the latest version of Windows 11 24 H2. I'm using NVDA 2024.4.2. I don't use any plugins. I'm using eSpeak NG as the synthesizer. Using the beta doesn't solve this problem. What comes to my mind is to add the registry change made by the bat file suggested by @ABuffEr to NVDA's core. Is this possible, i.e. what if NVDA changes the registry entries that prevent the sound card from sleeping when it's installed?

**Comment by harun-342** [comment]
The registry changes suggested here didn't fix my problem either. Unfortunately, even if this could be added to NVDA, it wouldn't help me.
