### ISSUE TITLE
firefox edit fields: duplicate llines and words

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3156]
**Reported by camlorn on 2013-04-15 15:15**
In Firefox 20.0.1 and NVDA main-5986:
When editing in edit fields, NVDA is sometimes deciding that lines are to be duplicated.  Specifically, it will sometimes read the previous line again instead of the next line.  If there is a post with four lines, it  may sometimes read line 1 twice followed by line 3 twice, skipping 2 and 4 entirely.  This is consistent, that is, it will always misread and skip the same lines, and when it starts it will always do it in pairs.  It will also sometimes decide that, when moving by word,  the first word of a line is the last word of the previous line, and seems to do so at the same times.
I've observed this very rarely in the NVDA ticket submission edit field.  It's common on audiogames.net forums and mudconnect.com forums, shows up on topmudsites.com forums, just to name a few, but can happen in any multiline edit field.  Moving by character seems to be unaffected, and selecting the text will report the correct lines and words.
This seems to be becoming more common for me.  Just as an additional piece of information, jaws 13 does this as well (it may be fixed in jaws; I've not used jaws for any significant period of time for about 2 months now).

**Comment by Adriani90** [comment]
@jcsteh I guess this is still an issue in last Firefox version. Right?
@camlorn please proviede exact stept to reproduce and an example website. I think there are some duplicate issue out there but we need exact steps to reproduce here.

**Comment by Adriani90** [comment]
Starting to understand this issue.
Current status:
1. Line by line navigation is mostly fixed in all browsers but it is still depending on type of edit field what a line is and how the cursor is moved when using up and down arrow keys. No specific issue here.
2. Paragraph navigation is fixed in every edit field with the new setting in document navigation category of NVDA, letting NVDA to define one or more line breaks as indication of a new paragraph
3. Navigation by page or screen with page up and page down, or home / end, this cannot be fixed in the browsers since the cursor moves vertically and not at the beginning of the line, so the navigation migh result in repetitions if there is no equivalent vertical position to move to. For this NVDA would need it own routine, as it provides for paragraph navigation.
4. Word by word navigation: NVDA would need its own routine, actually I can reproduce it in all browsers. Related issues are #3971 and #8057:
* In Chromium browsers with focus mode, NVDA repeats the punctuations before the line break character while in Firefox the punctuations are not recognized as words in the ctrl+left and right arro. navigation, so NVDA repeats the words before punctuation. 
* In all browsers, line feed character is not recognized as word itself in focus mode, so NVDA repeats the word / the punctuation before the line feed character.
* In browse mode though, NVDA recognizes line break characters as single words in the words navigation but not the punctuation.
Str:
1. Copy the text below into the comment edit filed of this issue
2. navigate with ctrl+arrow keys from the beginning to the end, in focus and browse mode.

Actual: 
* NVDA repeats words or punctuations when there are line breaks added in focus mode while using word navigation
* NVDA ignores punctuation in browse mode when using word navigation.

Expected:
* NVDA should treat line break characters in focus mode, and punctuations / symbols in browse and focus mode, as single words
* This behavior should be the default, changing the current symbol / punctuation level should not affect word navigation.
* one or more Space and white space characters next to each other should be sumarized and treated as a single word "blank"



"Hello,
    How are you?    




Fine   


And you?   
    


"

**Comment by Adriani90** [comment]
So I would restrict this issue for word by word navigation in general, since text navigation in focus mode with page up and down, home or end is not common in browsers.

If we restrict this issue to word by word navigation, then we could close this in favor of #8057.

cc: @jcsteh what do you think?

**Comment by CyrilleB79** [comment]
> So I would restrict this issue for word by word navigation in general, since text navigation in focus mode with page up and down, home or end is not common in browsers.

Maybe it's less common but it remains a bug. There is no reason to close; it may just be considered lower priority if it is less common.

Personally, I am using word by word nav, but also home/end.
I do not usually use pgUp or pgDown in focus mode, but maybe others do, e.g. people using web apps such as editors.

**Comment by XLTechie** [comment]
> Personally, I am using word by word nav, but also home/end.
> I do not usually use pgUp or pgDown in focus mode, but maybe others do, e.g. people using web apps such as editors.

Same for me. I use home/end all the time in text fields and textareas.

**Comment by jcsteh** [comment]
>     1. Line by line navigation is mostly fixed in all browsers but it is still depending on type of edit field what a line is and how the cursor is moved when using up and down arrow keys. No specific issue here.

There is still an issue in both Chrome and Firefox where if you're positioned at the end of a wrapped line, NVDA will report the next line instead of the current line. STR:

1. Open this test case:
    `data:text/html,<textarea cols="2">ab cd`
2. Focus the text box.
3. Press control+home.
4. Press end.
    - Expected: NVDA should say "blank"
    - Actual: NVDA says "c"
5. Read the current line (desktop: NVDA+upArrow, laptop: NVDA+l).
    - Expected: NVDA should say "ab "
    - Actual: NVDA says "cd"

Firefox at least supports the necessary IAccessible2 stuff to make this work correctly, but NVDA doesn't support it yet. I don't think Chrome does, but I'm not sure.

>     4. Word by word navigation: NVDA would need its own routine, actually I can reproduce it in all browsers.

I don't think this is correct. Different browsers have slightly different word navigation behaviour. That's not something NVDA should try to change. That said, the browse mode behaviour is not going to be consistent with focus mode word navigation and I don't think that's important.

>     * In Chromium browsers with focus mode, NVDA repeats the punctuations before the line break character while in Firefox the punctuations are not recognized as words in the ctrl+left and right arro. navigation, so NVDA repeats the words before punctuation.

I'm not sure what you mean about Firefox repeating punctuation here. Can you provide a smaller example demonstrating it?

>     * In all browsers, line feed character is not recognized as word itself in focus mode, so NVDA repeats the word / the punctuation before the line feed character.

It looks like Firefox treats the line feed character as a separate word for control+rightArrow, but Firefox accessibility doesn't treat the line feed as a separate word. That smells like a Firefox accessibility bug to me, though I need to dig a little further.

It looks like Chrome has the same bug. Terrific.

>     * In browse mode though, NVDA recognizes line break characters as single words in the words navigation but not the punctuation.

I don't see why this is a bug. It's a different choice, yes, but there's no clear rule that line feeds should be treated as words.

**Comment by Adriani90** [comment]
> I'm not sure what you mean about Firefox repeating punctuation here. Can you provide a smaller example demonstrating it?
Sorry I meant Firefox does not report punctuation in word by word navigation, in focus mode , only Chromium browsers do. And still they do it only if there is one punctuation sign. If there are 3 signs such as 3 question marks consecutively, they are sumarized as one word in the word navigation but NVDA does not report anything.
In contrast, Firefox just skips the signs and repeats the word when the carret lands on a line break and it actually treats the word and the punctuation signs as if they were one word all together. Take for example this:
```
Hello?


World???


Yes...
```

Actual: with ctrl+right arrow, in focus mode, NVDA repeats "hello", "world" and "yes" every time the carret lands on a line break.
Expected: NVDA should treat the punctuation and the linebreak as single words when pressing ctrl+right arrow, so the words are not repeated.
(i.e. NVDA should say on every ctrl+right arrow press:
"Hello, question mark, line feed, line feed, line feed, world, question mark, question mark, question mark, line feed"
and so on.

**Comment by jcsteh** [comment]
Just to clarify, do you have punctuation set to all? If you don't, you won't necessarily hear punctuation when moving by word.

In Firefox release, control+rightArrow in Firefox doesn't stop on punctuation at the end of words. It only stops on line feeds. That is intentional. As noted above, there's definitely a bug with accessibility reporting the wrong word for line feeds though.

There's an additional bug in Firefox Nightly related to punctuation; see https://bugzilla.mozilla.org/show_bug.cgi?id=1848282. That bug doesn't exist in Firefox release, though, and the related change won't ship to beta or release until this is sorted out. For now, if you're using Nightly, you can disable the problematic feature by setting intl.icu4x.segmenter.enabled to false in about:config.

**Comment by Adriani90** [comment]
> Just to clarify, do you have punctuation set to all? If you don't, you won't necessarily hear punctuation when moving by word.
no my punctuation is set to "some", but actually the punctuation setting should not affect character and word navigation. Actually the expected behavior for punctuation setting is to affect only navigation styles greater than word navigation.

> In Firefox release, control+rightArrow in Firefox doesn't stop on punctuation at the end of words. It only stops on line feeds. That is intentional.
what is the reason behind this?

> you can disable the problematic feature by setting intl.icu4x.segmenter.enabled to false in about:config.
Thanks very much for this hint.

**Comment by Adriani90** [comment]
> Different browsers have slightly different word navigation behaviour. That's not something NVDA should try to change. That said, the browse mode behaviour is not going to be consistent with focus mode word navigation and I don't think that's important.

Gotcha. Though I think at least in focus mode it might be worthy to find a routine that makes word navigation more consistent in edit fields in general. This does not affect only browsers, but all kinds of editors. The same problem we had for paragraphs which is now solved internally in NVDA core.

**Comment by CyrilleB79** [comment]
> no my punctuation is set to "some", but actually the punctuation setting should not affect character and word navigation. Actually the expected behavior for punctuation setting is to affect only navigation styles greater than word navigation.

No, this assertion is not true.
Today, punctuation level does not affect  character but affects all other types of navigation (word, line, paragraphe, etc.)

There are related discussions on this topic however in #8057 #10855  and #11779 .

**Comment by jcsteh** [comment]
> actually the punctuation setting should not affect character and word navigation. Actually the expected behavior for punctuation setting is to affect only navigation styles greater than word navigation.

That is only true if the chunk is a single character, since otherwise, you'd hear silence. For anything larger, the punctuation level applies.

> > In Firefox release, control+rightArrow in Firefox doesn't stop on punctuation at the end of words. It only stops on line feeds. That is intentional.
> 
> what is the reason behind this?

This was probably modelled on the way Windows standard Edit controls work. For example, if you open the Run dialog and type there, you'll notice that control+rightArrow doesn't stop on punctuation at the end of a word there either. Unfortunately, Microsoft have been pretty inconsistent since then. Newer text boxes (not standard Edit controls) seem to implement word navigation very differently.

> I think at least in focus mode it might be worthy to find a routine that makes word navigation more consistent in edit fields in general. This does not affect only browsers, but all kinds of editors. The same problem we had for paragraphs which is now solved internally in NVDA core.

I disagree. The screen reader should be making as few modifications as possible to the user experience of the app. Altering that too much is asking for confusion and incompatibility. Paragraphs might have been a reasonable exception because this simply isn't supported in many controls at all. In contrast, word navigation is supported across the board. Aside from anything else, trying to enforce consistent word navigation is likely to cause a pretty severe performance hit, especially for something like word navigation where one may want to move very fast.

**Comment by CyrilleB79** [comment]
@Adriani90, @jcsteh and @camlorn, this issue is about to be closed by #16745. However some related but distinct issues have been raised in the current issue. Could you check if they are still relevant and open a dedicated issue for each of them if needed?

**Comment by jcsteh** [comment]
1. I don't think that PR will fix #9305, which has been closed as a duplicate. That probably needs to be fixed in Chrome and is likely related to fetching boundaries near punctuation/line feeds in general, rather than being specific to the caret at the end of the line.
2. In both Chrome and Firefox, a line feed isn't treated as a word by accessibility, even though moving the cursor by word stops on a line feed. That needs to be fixed in both Chrome and Firefox and again isn't specific to the caret.
3. Word boundaries being inconsistent between apps (and inconsistent with browse mode) is IMO not a bug and not something we should try to fix, as doing so would override the behaviour of the app. What we do want is for word boundaries to be consistent in a given app for both cursor navigation and accessibility.

**Comment by jcsteh** [comment]
> In both Chrome and Firefox, a line feed isn't treated as a word by accessibility, even though moving the cursor by word stops on a line feed.

For Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1904999

**Comment by ahicks92** [comment]
(I used to be Camlorn).

@jcsteh 
I don't have the reference handy but VSCode opened an issue about this years ago and got no traction from Google.  Try moving by word over C++ and Rust code. It's fun.

@CyrilleB79 
Can you tell me what we need to check specifically, I don't even remember this issue.  I also don't run betas anymore and can't build from source for some reason or other.  Looking at my original comment that's actually worked fine for years now as it is.

It has been over a decade, sorry.  And I'm short on time right now.

**Comment by CyrilleB79** [comment]
@ahicks92 I was referring to https://github.com/nvaccess/nvda/issues/3156#issuecomment-155306270.

Is all this fixed in [last alpha](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-32650,405f9bfa.exe)?

If it is fixed, or it does not matter anymore for you, just ignore this.
If it is not fixed, open an issue to explain the remaining issue.

Note: when running last alpha, you may get a warning from Windows Defender; this is [expected](https://groups.io/g/nvda-devel/topic/windows_defender_warning/106923899), just run anyway.
