### ISSUE TITLE
Text is corrupted when using AutoHotKey abbreviation-expansion with NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4499]
**Reported by andrewd on 2014-09-29 04:12**
If abbreviation-expansion is coded as follows:
::ad::My name is Andrew
the expanded text is usually missing character(s).  If coding:
:b0:ad::My name is Andrew
is used the abbreviation characters, are not deleted and the presence of NVDA does not result in lost characters.  It is then necessary to delete the characters manually, which somewhat defeats the purpose of the facility.
I use an AutoHotKey script to put HTML tags into a file.  This involves opening and closing tags with an intervening blank line and this exacerbates the problem.  The following works on my machine:
:b0:pg::
Send, {home}
Sleep 200
Send, <p>`n`n
Sleep, 300
Send, </p>`n
Sleep, 300
Send, {del 3}
Send, {up 2}
Return
If selecting from a menu or hotkey instead of using the abbreviation, the following works well:
Send, <p>`n`n</p>`n{up 2}
Return
Other screen readers don't have this issue.  Turning off speech or turning on sleep mode does not help.
Unless this has wider implications, it is a very minor issue.

**Blocked by #2953**
**Blocking #5144**

**Comment by bhavyashah** [comment]
@michaelDCurran's https://github.com/nvaccess/nvda/issues/4499#ref-commit-7b7823c and @jcsteh's https://github.com/nvaccess/nvda/issues/4499#ref-commit-b6a4273 include commits. Are they indicators of further progress on this ticket, or has all of Jamie's earlier work been reverted due to problems? Also, should we give up in case of this ticket and close as cantfix, or do @leonardder, @derekriemer, @josephsl, @dkager and others have further thoughts/inputs? If implementation cost is too high for what this ticket's worth, we may wish to mark as a P4.

**Comment by derekriemer** [comment]
I think this is fixed, but we need @jcsteh or @michaelDCurran to confirm.

**Comment by jcsteh** [comment]
No. The fix for this was reverted in 171a430, since it didn't actually work. Setting as p4, since this affects few users, has a work around (disable Handle keys from other applications) and appears to be very difficult to even diagnose.

**Comment by AllenChen-Xingan** [comment]
I use the latest NVDA version in 22.4, which prevents any of text expansion apps. I tried espanso, text-expander, when triggering the text replacement under the NVDA, it just replaces the abbreviation into space rather than the correct replaced text.

**Comment by Adriani90** [comment]
@AllenChen-Xingan just to be on recent updates, I guess you are still having this issue in 2024.4 beta right?
What happens if you increase the timeout on cursor movements in NVDA advanced settings?
cc: @SaschaCowley

**Comment by Adriani90** [comment]
No updates from people who could reproduce this upon request since more than 2 years, closing as abandoned. if you are still having this issue, please comment and we can reopen.
