### ISSUE TITLE
Update Check: Certificate verification failure when downloading snapshots

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5871]
In Summary:

Upon an update check being performed, I think logging certain information about the steps carried out by NVDA could greatly assist whilst diagnosing any potential issues that may occur. Whilst understandably it may not make all that much sense to provide output within any error dialogs which may appear, this could be logged so that the user can easily paste this information into an email/issue, etc.

In Depth:

This issue became apparent several days ago when I was in the process of updating NVDA on two machines, both running Next 13096,1c5884d. Whilst one machine updated without issue, I'm currently having a problem whereby the other simply refuses to download the update package after the "Not Now" button has been clicked within the Donation window; I'm simply presented with an error dialog stating that an error downloading the update occurred. Setting the log level to Debug unfortunately doesn't provide me with any useful information - strangely, however, this even occurs after manually downloading an update package, applying the new version, and once again checking for updates. Both machines have been configured exactly the same, and I've been able to carry out an update from within NVDA on this machine before without issues and whilst it's still possible to update my installed copy manually, I'd like to get to the cause of this issue if at all possible.

**Comment by jcsteh** [comment]
Information about any errors should already be included in the log. This 
is obviously going to be somewhat technical. Are you saying an error was 
logged but you weren't able to glean any useful details from it? Or are 
you saying you didn't see an error in the log? If you can't find the 
error, perhaps you could provide a log at level input/output and we can 
take a look.

**Comment by elliott94** [comment]
The error wasn't the standard type (i.e. the sound wasn't triggered) - it was a dialog presented within the main window itself.

Before checking for updates, I set the log level to Debug and didn't see any useful information - am I right in thinking that Debug is a higher level than Input/Output?

I can provide a log when the next snapshot is generated - I'm currently running the latest Next version from a manual install.

**Comment by jcsteh** [comment]
A dialog is presented, but an error is also logged.

Yes, debug is higher than input/output. However, even level info should 
have been enough.

**Comment by elliott94** [comment]
I'm pretty sure that I definitely checked the log when the error occurred, but I'll do some more testing when the next snapshot is built. It's very strange - I've never seen anything like it before.

**Comment by elliott94** [comment]
Ok... some results!

After checking for updates and once again clicking the Download Update button, the resulting error didn't generate anything in the log when set to Info. However, I received the following in Debug:

DEBUGWARNING - updateCheck.UpdateDownloader._bg:
Error downloading https://ci.appveyor.com/api/buildjobs/1qlux60vhvvqs9m2/artifacts/output/nvda_snapshot_next-13291,ce9a7e69.exe
Traceback (most recent call last):
  File "updateCheck.pyc", line 304, in _bg
  File "updateCheck.pyc", line 324, in _download
  File "urllib.pyc", line 87, in urlopen
  File "urllib.pyc", line 213, in open
  File "urllib.pyc", line 443, in open_https
  File "httplib.pyc", line 1053, in endheaders
  File "httplib.pyc", line 897, in _send_output
  File "httplib.pyc", line 859, in send
  File "httplib.pyc", line 1278, in connect
  File "ssl.pyc", line 352, in wrap_socket
  File "ssl.pyc", line 579, in __init__
  File "ssl.pyc", line 808, in do_handshake
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

This is really strange - I recall certificate verification being added to make sure that NVDA was connecting to the correct server without the possibility of the request being intercepted, but this was added before the move to AppVeyor. Also, one of my machines is able to download the update without issue, and as previously mentioned I've fetched multiple updates with this machine before... but that was before the AppVeyor move.

**Comment by jcsteh** [comment]
Oh. Right. Yes, it's a debugWarning because an update can actually try multiple download URLs, and just because one fails doesn't mean the whole thing fails, so we don't want to log it as an error.

The reason this is happening is that Windows hasn't downloaded the trusted root security certificate used by AppVeyor on your system. We worked around this in #4803, but only for the NV Access server. I neglected to realise this might affect AppVeyor when we started using that.

**Comment by nvaccessAuto** [comment]
Incubated in 7fa8a3bf1028c8d31bed271c48b59e7ae7bde518.

**Comment by elliott94** [comment]
Thanks for fixing this - however, I'm still having problems.

When attempting to update from Next 13295,e829abde (which has the fix present), the following error occurs:

ERROR - updateCheck.UpdateDownloader._bg:
Error downloading https://ci.appveyor.com/api/buildjobs/klwt5nc85xmjbviv/artifacts/output/nvda_snapshot_next-13300,9ab71476.exe
Traceback (most recent call last):
  File "updateCheck.pyc", line 295, in _bg
  File "updateCheck.pyc", line 318, in _download
  File "updateCheck.pyc", line 537, in _urlopen
NameError: global name 'url' is not defined

Interestingly, it doesn't appear that this is now an SSL error - I was once again able to successfully update on another machine without issues.

**Comment by derekriemer** [comment]
This is probably a bug.

On 4/24/2016 9:54 AM, elliott94 wrote:
>
> Thanks for fixing this - however, I'm still having problems.
>
> When attempting to update from Next 13295,e829abde (which has the fix 
> present), the following error occurs:
>
> ERROR - updateCheck.UpdateDownloader._bg:
> Error downloading 
> https://ci.appveyor.com/api/buildjobs/klwt5nc85xmjbviv/artifacts/output/nvda_snapshot_next-13300,9ab71476.exe
> Traceback (most recent call last):
> File "updateCheck.pyc", line 295, in _bg
> File "updateCheck.pyc", line 318, in _download
> File "updateCheck.pyc", line 537, in _urlopen
> NameError: global name 'url' is not defined
>
> Interestingly, it doesn't appear that this is now an SSL error - I was 
> once again able to successfully update on another machine without issues.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5871#issuecomment-213987905>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by elliott94** [comment]
That may be the case - interestingly though, I upgraded from the exact same snapshot successfully on another machine so I wonder what could be causing the error to appear.

**Comment by jcsteh** [comment]
Sorry; this was a rather stupid coding error on my part. Unfortunately, 
it's very difficult for me to test this, as my machines all have the 
right certificate already. I'll try to fix this as soon as I can.

**Comment by nvaccessAuto** [comment]
Incubated in 411ff2c40dc096ea63ffc9d49ac5ee98bed44035.

**Comment by derekriemer** [comment]
You should be able to grab an update after the next build of a snapshot 
to get this fix.


On 4/27/2016 10:59 PM, NV Access automation wrote:
>
> Incubated in 411ff2c 
> <https://github.com/nvaccess/nvda/commit/411ff2c40dc096ea63ffc9d49ac5ee98bed44035>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5871#issuecomment-215310317>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
Ug. I've managed to reproduce this on a vm and aside from another coding 
error on my part, this fix still isn't sufficient. I'll need to think on 
this some more.

**Comment by elliott94** [comment]
Just out of interest, does this also mean that users who don't currently have the necessary certificate present on their system would have potentially had issues when snapshots were hosted locally on the NV Access server? Would this not also effect release versions?

**Comment by jcsteh** [comment]
No, because there's code in NVDA to fetch the required certificate for 
nvaccess.org; see #4803. The change I'm trying to make here is to fetch 
the certificate for AppVeyor, but now that my silly errors are fixed, 
the problem is that AppVeyor then redirects to Google Cloud Storage, 
which requires yet another certificate fetch. I haven't worked out yet 
how I'm going to catch the redirect and do yet another certificate 
fetch. This is all very tedious; it would be a lot easier if Python just 
handled this transparently like it should.

**Comment by elliott94** [comment]
I was thinking about this some more today. In theory, if it's Python making this more difficult than it should be would it not be possible to automatically force the NV Access server to pull the latest snapshot from AppVeyor when its built, and then revert snapshots to downloading from that particular server? Since for now new release versions are hosted independently of GitHub, this should hopefully alleviate the issues with forcing the certificate to download when a redirect from AppVeyor to Google is performed.

**Comment by jcsteh** [comment]
> would it not be possible to automatically force the NV Access server to pull the latest snapshot from AppVeyor when its built, and then revert snapshots to downloading from that particular server?

It's possible, but complicated. AppVeyor allows us to keep a lot more snapshots than we could previously and we don't want to lose this. However, this would require us to keep the last snapshot for each branch while still keeping the AppVeyor URL around so we can use it in the index when a new snapshot arrives.

> Since for now new release versions are hosted independently of GitHub

No; they're hosted on our server.

By the way, you can easily work around this issue by opening the download link for at least one snapshot in Internet Explorer. That will cause Windows to fetch the certificates. This won't work with Firefox or Chrome, as they do their own certificate handling.

**Comment by Adriani90** [comment]
@elliott94, @jcsteh I guess this issue is still existing. Right?

**Comment by elliott94** [comment]
Yes - this can still be observed with latest snapshot builds.

**Comment by leonardder** [comment]
@jcsteh: might this be something that the migration to Python 3 could somehow fix or improve?

**Comment by jcsteh** [comment]
I doubt it. The underlying cause of this is https://bugs.python.org/issue20916 , which isn't fixed in Python 3. The code we have to work around this for releases is just that, a workaround. Unfortunately, it fails for snapshots because AppVeyor redirects to another URL and this workaround can't intercept and deal with redirects.

**Comment by Brian1Gaff** [comment]
> 
> 
> That may be the case - interestingly though, I upgraded from the exact same snapshot successfully on another machine so I wonder what could be causing the error to appear.

Re: [nvaccess/nvda] Alpha updates have stopped working (#11225)
this has happened all over again here.
 Brian

**Comment by Adriani90** [comment]
That issue in Python is still open and has been migrated to Github. The most current link is this one:
https://github.com/python/cpython/issues/65115

**Comment by Adriani90** [comment]
cc: @gerald-hartig, @seanbudd is this still an issue now with the current python version?

**Comment by gerald-hartig** [comment]
@Adriani90 Testing python 3.11 on my local machine with the minimal example in the python ticket you linked to does not return an error. I suspect this can therefore be closed.

**Comment by Adriani90** [comment]
Thanks for the update, I am closing. If anyone still has this issue, they can comment and we can reopen later on.

**Comment by jcsteh** [comment]
> Testing python 3.11 on my local machine with the minimal example in the python ticket you linked to does not return an error. I suspect this can therefore be closed.

Does that minimal example account for the possibility that the root certificate in question has already been downloaded into the Windows certificate store by some other application? In that case, Python certificate verification will succeed because the system already has the certificate. This problem only occurs if some other (non-Python) app didn't cause the system to fetch the relevant certificate.
