### ISSUE TITLE
Web Browser Dialogues Do Not Appear Inline

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5968]
In places such as Facebook where dialogues often appear in web browser documents, it is not a common command to have to scroll to the very end of a document to have to interact with it. Such dialogues may not appear at the bottom of the screen for sighted users. Particularly in screen layout view, when having to interact with inaccessible dialogues, especially in dialogues where system states a program isn't responding, almost always followed by a non responsive window of any kind, where no feedback is seen, such is becoming more and more apparent in Mozilla Firefox and other chrome based gecho browsers.

**Comment by jcsteh** [comment]
If a dialog doesn't get focus on a website, this is an accessibility problem with the website in question and needs to be reported to the website author. There is litle NVDA can do to work around these problems without breaking other correctly implemented sites.

**Comment by Elshara** [comment]
This is an issue Facebook even has. The issue is where the dialogue
appears, and it's lack of labels explaining what field is what. It is
consistent across many websites for the type of dialogue it generates,
I don't know it's technical name.

**Comment by PratikP1** [comment]
These are typically referred to as “modal dialogs.” Good web development techniques can allow developers to insert modal dialogs in the source order where they would make the most sense. While it is true that many developers do not do a good job of inserting them in the right place, it is not, nor should it be, the screen reader’s job to put them where they supposedly belong. These kinds of screen reader hacks were tried earlier and caused many more problems. Standards must be followed.

**Comment by Elshara** [comment]
I agree. But they make me deter from using social media because
they're constantly using them now. That's why I started my own site,
but I can't even get away from it when I want to edit something using
a text editor solution coming from tinymce. It's beyond frustrating
especially when the dialogue jumps around and there's no stable
navigation. It's not all the developers fault, it has to also do with
how it appears in Firefox and how NVDA could if possible, relocate it
to where it makes sense and is stable.

**Comment by jcsteh** [comment]
If a dialog gets focus (which it should if it's meant to accept input 
from the user), there's no need to relocate anything. You talk about 
"jumping around", but you don't actually explain what you mean or give 
an example. There are accessibility standards which allow dialogs to be 
fully accessible, so if they aren't accessible, it is almost certainly 
author error.

The only issue I've seen on Facebook is that dialogs that contain 
document-like content don't get marked as documents. You can override 
this and force browse mode by pressing NVDA+space.

Trying to second guess the author's intent is problematic for two 
reasons. First, there have to be heuristics to work out what you 
actually want, which is going to be different in almost every case. 
Second, a heuristic applied incorrectly can cause major problems for 
other cases.

**Comment by Elshara** [comment]
This is true. Developers working with newer access technologies make
things more visually appealing all the time so being able to just rely
on text like in the old days is becoming a thing of the past. We're
keeping up for sure but I think the jumping around may be the cause of
some websites trying to have animated dialogues rather than static or
fixed ones. Not to worry, I'm not really using FB much so I just
thought I'd put it out there if anyone else seems to be facing trouble
with the dialogue placement especially when someone expects an action
to be performed inline especially if they used to be able to do so at
one point on the same website, but now are unable to because of how
the dialogues appear. On face book, at least the dialogues are ones
that pop up automatically.

**Comment by jcsteh** [comment]
I'm still not sure what you mean by jumping around or strange locations. 
At least for Facebook, the dialog gets focus, so you don't have to worry 
about where it's located; it's right in front of you. Can you please 
give thorough detail concerning the issue you're having in Facebook? 
Also, what browser are you testing with?

**Comment by Elshara** [comment]
Browser is Firefox. The issue happens a lot where animated content
appears. Like in auto scrolling situations.

**Comment by PratikP1** [comment]
Please provide a specific site and a circumstance where this appears. Animation and modal dialog boxes generally have nothing to do with each other in web development. It would be helpful if you could provide: 1. Descriptions. 2. Specific sites and steps to reproduce the problem you’re seeing. Investigation of specifics could lead to a better understanding of the problem. Rather than speculating on the cause with little knowledge of web development, it would be optimal to determine whether this is a specific problem that NVDA can solve.

**Comment by Elshara** [comment]
Well, one of the absolute worst offenders for the jumping issue is the
add this tool bar. It's on a ton of websites.
1. When the tool bar appears, trying to scroll to the end of it always
results in a huge cursor jump. No matter what website the tool bar is
on.
The only way to solve the issue is to do a read or say all command
insert plus b to prevent it while the tool bar is not focused on the
more services link.
Some websites make their side bars appear before the actual content so
usually the add this tool bar is a part of the content prior to the
main article.
This would prove my animation theory effecting NVDA being able to not
function correctly while autoscrolling.
An example website of auto scrolling content is found here.
http://jqueryhelp.ning.com
Go to the members tab, then scroll down to the RSS link. About there
is where NVDA starts to majorly jump the cursor around wildly as the
content scrolls. This is not the only place this happens.
For the add this tool bar, any major article site has this installed.
For example.
http://shatteringthematrix.com/
Scroll down to where it says networking toolbox. A few lines below
that, you will notice the jumping. You will all of a sudden be taken
directly to the very bottom of the page.
As for the dialogues, try managing a Facebook page, a Facebook group,
a Facebook app. Or even adding a friend. This functionality is either
so badly coded or so poorly recognized in NVDA that in order for you
to get back to the cursor, there is no closing Facebook dialogues. You
have to assuming your browser is in maximized mode, hit control l to
bring up the navigation toolbar then tab to the actual document by
skipping over the browser toolbars in the process just to accomplish
one simple task over there.
Google applications are even worse. If you try to upload a Youtube
video, you have to literally turn off NVDA to stop the browser from
reporting every nano second a message that NVDA can never fully read
because the notification progress bar keeps on repeating itself during
the video upload process.
These are just a few of the various browser functions NVDA has a problem with.

**Comment by jcsteh** [comment]
Okay. The reason this is getting confusing is that these are actually three entirely separate issues, even if they don't seem that way.

1. Regarding the Add This toolbar, that one isn't a dialog. When focus hits a certain point, the toolbar incorrectly bounces focus somewhere else. That said, we're hoping that the eventual fix for #2039 will work around this.
2. Regarding Facebook, I still don't understand this one. Yes, a dialog gets focus, but there's no need to move the cursor anywhere because the dialog got focus. The one issue here is that you can't use browse mode there because they don't mark it as a document, but as I said earlier, you can override that with NVDA+space.
3. The Youtube bug is due to inappropriate use of alerts by Google. I'm pretty sure we reported this one to Google, so I'll see if I can give them a nudge on that.

**Comment by Elshara** [comment]
Solving this would make a lot of things more accessible for a lot of
users. Sorry for the 3 separate issues. One thing kind of lead to
another.

**Comment by PratikP1** [comment]
I’ve seen many people report the video upload alert issue to Google. In fact, I did it two years ago. It does not seem like it’s a high priority to them.

**Comment by Elshara** [comment]
I've stopped using youtube because they cancelled their upload by web cam.
