### ISSUE TITLE
NVDA not leaving focus mode when focused element is removed from DOM

### ISSUE THREAD

**Issue by ZachPeters** [nvaccess/nvda#6074]
When a div element with the role of "menuitem" is focused NVDA enters focus mode. If this div is removed from the DOM without being unfocused, NVDA does not leave focus mode and you can no longer move through the elements on the page with the arrow keys.
I have provided an html page (nvda_focus.html) which shows this behavior. When you click on the button "Add menuitem div" with spacebar or enter, a new menuitem is added to the document which becomes focused, and NVDA enters focus mode. Now if you press any button this div is removed, but NVDA does not leave focus mode.

My questions are:
Is this expected behavior? 
Is there a way to programmatically make NVDA leave focus mode and return to browse mode?

[nvda_focus.zip](https://github.com/nvaccess/nvda/files/316527/nvda_focus.zip)

**Comment by jcsteh** [comment]
> Is this expected behavior?

It's not intended, but it's known.

* It's partially a browser bug. For Firefox, it's due to [Mozilla bug 559561](https://bugzilla.mozilla.org/show_bug.cgi?id=559561); in short, we don't get any focus event when the focused element is removed. There may be similar bugs in other browsers.
* Even if that were fixed, we don't currently return to browse mode when the document gets focus. That is probably something we should address here.

> Is there a way to programmatically make NVDA leave focus mode and return to browse mode?

Focus something in the document that doesn't require focus mode; e.g. a link, a focusable heading/div, etc.

**Comment by jcsteh** [comment]
> Even if that were fixed, we don't currently return to browse mode when the document gets focus. That is probably something we should address here.

This can be reproduced as follows:

1. Open a private browsing window and go to google.com. (The private browsing window ensures Google Instant is enabled.)
2. Type something in the search box and press enter.
 * Expected: NVDA should switch to browse mode.
 * Actual: It remains in focus mode.

**Comment by derekriemer** [comment]
Should this actually happen? If your typing, you don't want it to go 
into browse mode while typing.


On 6/28/2016 1:12 AM, James Teh wrote:
>
>     Even if that were fixed, we don't currently return to browse mode
>     when the document gets focus. That is probably something we should
>     address here.
>
> This can be reproduced as follows:
>
>  1. Open a private browsing window and go to google.com. (The private
>     browsing window ensures Google Instant is enabled.)
>  2. Type something in the search box and press enter.
>       * Expected: NVDA should switch to browse mode.
>       * Actual: It remains in focus mode.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6074#issuecomment-228969864>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivXjz-jqBdRXpaHuHvik2fxb0EBoaks5qQMlxgaJpZM4I2gXE>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment]
If the document gets focus, typing isn't going to have any effect, since 
the input field is no longer focused.

**Comment by Adriani90** [comment]
This is also still reproducible in all browsers with NVDA 2019.2 Beta 3.

**Comment by Adriani90** [comment]
cc: @feerrenrut

**Comment by Adriani90** [comment]
The Firefox bug has been fixed in Firefox 106.

Testing with NVDA 2025.1.2 RC in all main browsers, the behavior is the same:
NVDA does not switch to browse mode after element is removed from DOM, but you can switch to browse mode directly by pressing tab, nvda+space bar or escape.
I wonder whether it is the responsibility of the web authors to redirect system focus to something taht makes sense (e.g. the link "skip to content" at the top of many websites)? In this case automatic switch to browse mode would apply.

But yeah, ideally NVDA should switsch to browse mode automatically at the same position where it was before switching to focus mode.
@jcsteh is it  possible to call sync system focus to focussable elements at the position of the virtual cursor automatically after the element has been removed from DOM? Currently we call this function manually by pressing nvda+space bar, but this use case could be an exception where it happens automatically.
