### ISSUE TITLE
NVDA too slow to navigate the task manager, and repeating information

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6245]
Good evening everyone.
I follow with aniverçário update findings from windows 10.
Using NVDA next 13483 and 64-bit windows windows 10.0.14393, to navigate the task manager occur 2 errors.
What bothers you most is slow NVDA to read while walking with arrows or tabe, about a 5/2.
Another problem is that NVDA repeated several times the same information.
Hall to play:
Open the task manager.
Enable function details.
Now navigate with arrows from the task list, NVDA takes to speak the items, and repeats the same information several times.
The same applies to navigate tabe to end a task as an example, or also occurs when you press shift + tabe to the page tab and switch to other tabs with arrow right, other guides booting, details, ETC.
Regarding the slow, my machine is a core v 1800MHZ with 4GB of ram.

Annex also a log with all the add-ons disabled NVDA, I disabled the NVDA complements the window to turn off NVDA.
Sorry for the trouble log and my text, I speak in Portuguese only, and suffered, as you see, laughs.
Thank you.

**Comment by fernando-jose-silva** [comment]
[tarefas.txt](https://github.com/nvaccess/nvda/files/404877/tarefas.txt)

**Comment by Brian1Gaff** [comment]
This is interesting as on the latest next snap on xp  task manager seems 
more sluggish than on the release version as well.
 I do know that this part of the system will often read when other software 
appears not to wrk any more so it could just be an accident of what else 
might be running in the background. One needs to look at the idle parameters 
to see if there is a good amount of resources still available or whether 
something unrelated has become stuck.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by fernando-jose-silva** [comment]
Good afternoon, I checked, and my idle time if the system is 20%.

**Comment by ehollig** [comment]
@fernando-jose-silva, is this still an issue on the latest version of Windows 10 and the latest version of NVDA? I am not able to reproduce the behavior you describe.

**Comment by leonardder** [comment]
I can also reproduce a significant slow down of NVDA when opening the Task Manager under both Fall Creators update systems. That is, it takes a lot of time before NVDA is successfully able to navigate the task manager, and even then, performance is not ideal.

**Comment by fernando-jose-silva** [comment]
Yes, still experimental slowness when using Task Manager, thank you.


Enviado do meu iPhone

Em 24 de out de 2017, à(s) 03:19, Leonard de Ruijter <notifications@github.com> escreveu:

> I can also reproduce a significant slow down of NVDA when opening the Task Manager under both Fall Creators update systems. That is, it takes a lot of time before NVDA is successfully able to navigate the task manager, and even then, performance is not ideal.
>

**Comment by Neurrone** [comment]
Until Microsoft fixes this long standing issue, installing the windows 7 task manager files](https://winaero.com/blog/get-classic-old-task-manager-in-windows-10/) works very well - no lag, and perfectly accessible.

**Comment by Adriani90** [comment]
I can confirm that the add-on Windows 10 app essentials by @josephsl fixes the double or tripple reporting issue. I hope this fix will be integrated into NVDA itself soon.

**Comment by Adriani90** [comment]
Apart from that, NVDA 2019.1 Beta 1 is very responsive in the task manager in Windows 10 1809 update. So this is not an issue anymore.

**Comment by Adriani90** [comment]
Now the entries are not repeated anymore, even without Win10 Apps addon it works correctly. However there is another issue with the task manager. NVDA crashes when I open the task manager via ctrl+alt+del on Windows 10 1909 Update.

**Comment by Adriani90** [comment]
NVDA crashes completely and I get following error, cc: @feerrenrut 
```
IO - inputCore.logTimeSinceInput (22:17:22.318) - MainThread (2788):
0.109 sec since input
IO - speech.speak (22:17:22.319) - MainThread (2788):
Speaking ['Task-Manager', 'Reihe 1', 'Spalte 2']
IO - inputCore.logTimeSinceInput (22:17:22.571) - MainThread (2788):
0.362 sec since input
IO - speech.speak (22:17:22.571) - MainThread (2788):
Speaking ['Task-Manager']
IO - inputCore.logTimeSinceInput (22:17:23.236) - MainThread (2788):
1.026 sec since input
IO - speech.speak (22:17:23.236) - MainThread (2788):
Speaking ['Spaltenüberschrift', 'Überschrift']
IO - inputCore.logTimeSinceInput (22:17:23.248) - MainThread (2788):
1.040 sec since input
IO - speech.speak (22:17:23.248) - MainThread (2788):
Speaking ['Name Sortiert (aufsteigend)']
IO - inputCore.logTimeSinceInput (22:17:23.381) - MainThread (2788):
1.172 sec since input
IO - speech.speak (22:17:23.381) - MainThread (2788):
Speaking ['Name Sortiert (aufsteigend)', 'Überschrift']
IO - inputCore.InputManager.executeGesture (22:17:24.309) - winInputHook (6532):
Input: kb(laptop):shift+tab
ERROR - NVDAObjects.__call__ (22:17:26.052) - Dummy-454 (5512):
Exception in chooseNVDAObjectOverlayClasses for <'taskmgr' (appName 'taskmgr', process ID 6500) at address 6e0a30>
Traceback (most recent call last):
  File "NVDAObjects\__init__.pyc", line 95, in __call__
  File "appModules\taskmgr.pyc", line 31, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1282, in _get_presentationType
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 741, in _get_presentationType
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1216, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 835, in _prefetchUIACacheForPropertyIDs
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
ctypes.ArgumentError: argument 1: <class 'RecursionError'>: maximum recursion depth exceeded in __instancecheck__
```

NVDA alpha-20097,6a573cd9

**Comment by lukaszgo1** [comment]
@Adriani90 Have you tested with all add-ons disabled? There was a similar issue with Columns review a while back.

**Comment by Adriani90** [comment]
Oh thanks for the hint, Tested with columns review disabled and the error does not occur. NVDA does not crash. However, now after a restart the issue is still as described here initially , NVDA repeats the entries in the list three times and it is somehow sluggish in the task manager.
cc: @ABuffEr

**Comment by ABuffEr** [comment]
Hi all,
I fixed ColumnsReview issue some builds ago (disabling it in task manager), please update from download link in [its Github page.](https://github.com/abuffer/columnsReview)

**Comment by leonardder** [comment]
Performance is still far from perfect, if not very bad in Task Manager. Confirmed by @zersiax that the current slowness seems to be NVDA specific.

**Comment by leonardder** [comment]
Related to #11109, #11077, #11002, #9465

**Comment by beqabeqa473** [comment]
Hello.

What is the current state of this issue?
I think nothing specific happened for several years in this case.

**Comment by Adriani90** [comment]
@fernando-jose-silva how is now the experience with NVDA last alpha version?

You can download and test with the last alpha version at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by gregjozk** [comment]
using nvda 2022.4 and win10 22h2 and task manager is still problematic. as I watched development, between this version and current alpha, there is no improvement regard the task meneger, but may be I'm missing something. so in my opinion this issue is actual and valid.

**Comment by Adriani90** [comment]
See #14701Von meinem iPhone gesendetAm 03.04.2023 um 17:43 schrieb gregjozk ***@***.***>:﻿
using nvda 2022.4 and win10 22h2 and task manager is still problematic. as I watched development, between this version and current alpha, there is no improvement regard the task meneger, but may be I'm missing something. so in my opinion this issue is actual and valid.

**Comment by fernando-jose-silva** [comment]
I no longer have this problem, however I believe it is important to hear from others who still have this problem before closing this call.  thanks.

**Comment by beqabeqa473** [comment]
Hello.

Latest NVDA alpha.
open task manager.
go to performance tab.
try to navigate with tab key.
NVDA tries to announce item three times
tried to identify the root cause, event tracker addon shows that item is beeing focused then loosing focus then focused once more then again loosing focus and then finaly once more gaining focus.
without running addons situation is the same.
Because of this performance degrades very strongly.
using windows 10 latest updates.

**Comment by beqabeqa473** [comment]
As title says: NVDA too slow to navigate the task manager, and
repeating information.
Not all aspects of this issue is fixed, so don't think it is correct
to close it.
Btw, it is still sluggish on normal processes tab, so sluggishness
also is not fixed.

On 9/26/23, Sean Budd ***@***.***> wrote:
> Closed #6245 as completed via da4e3a2f75fce48162ce4daf7c96872c3678fbc4.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6245#event-10469135437
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by seanbudd** [comment]
Could you please explain which parts of the issue are still relevant?

This issue is a bit of a mess, if possible, a new issue using the issue template outlining the current problems would be ideal.

**Comment by seanbudd** [comment]
It might be worth declaring the entire appmodule as bad for UIA

**Comment by beqabeqa473** [comment]
information is beeing repeated when pressing tab, and needed
information is not read by nvda like cpu load an gpu, and ram, in
performancd tab, in processes tab nvda is very sluggish.
These all are issues on win10. Repeating is also the problem of win11.
don't know about processes tab though.

On 9/26/23, Sean Budd ***@***.***> wrote:
> It might be worth declaring the entire appmodule as bad for UIA
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6245#issuecomment-1734819541
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment]
Given the valuable discussion here and clear details on how to reproduce, this needs more testing and validation from the community that this is fixed before closing it. I am reopening.

**Comment by seanbudd** [comment]
@beqabeqa473 which version did you test with? This fix is not on alpha yet, but will be soon. It is currently only in beta3.

**Comment by beqabeqa473** [comment]
This issue was before leonard made changes in terms of removing
SysListView from bad UIA window.
I will test of course when it will be in alpha and will back with results.

On 9/26/23, Sean Budd ***@***.***> wrote:
> @beqabeqa473 which version did you test with? This fix is not on alpha yet,
> but will be soon. It is currently only in beta3.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6245#issuecomment-1734994720
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
Ok, this issue is not only about listview, so issue is not fixed.

On 9/26/23, Beqa Gozalishvili ***@***.***> wrote:
> This issue was before leonard made changes in terms of removing
> SysListView from bad UIA window.
> I will test of course when it will be in alpha and will back with results.
>
> On 9/26/23, Sean Budd ***@***.***> wrote:
>> @beqabeqa473 which version did you test with? This fix is not on alpha
>> yet,
>> but will be soon. It is currently only in beta3.
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/6245#issuecomment-1734994720
>> You are receiving this because you were mentioned.
>>
>> Message ID: ***@***.***>
>
>
> --
> with best regards Beqa Gozalishvili
> Tell: +995593454005
> Email: ***@***.***
> Web: https://gozaltech.org
> Skype: beqabeqa473
> Telegram: https://t.me/gozaltech
> facebook: https://facebook.com/gozaltech
> twitter: https://twitter.com/beqabeqa473
> Instagram: https://instagram.com/beqa.gozalishvili
>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment]
@gregjozk, @@zersiax, @beqabeqa473 is this still an issue in NVDA 2025.1 Beta? I think there were some fixes regarding bad UIA window in between, so this should be much better actually.
Note that Windows 10 will reach end of life in Oktober 2025.

**Comment by Adriani90** [comment]
upon request, No updates from users who could reproduce it before since more than 1.5 years. Closing as abandoned.
If you are still having this issue in Windows 11, please comment and we can reopen.
