### ISSUE TITLE
Crashh in edge overlay in create new account wizard

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6311]
STR:
1. Open settings with win+i
2. accounts tab.
3. go to the Create an account item (may be called add people to this pc) (Different win10 levels do this differently).
4. press that button. An edge overlay appears, and NVDA says pane, and then document, and shows a progress bar. Eventually after about 5 seconds, the edge overlay crashes.
5. Turn NVDA off, and repeat step 4 with narrator. No crash should occur.

This occurs on windows ten builds 14393 and 14105 (I've confirmed on both). I'll update this ticket after i compile and run edgeRS1 to see if this fixes it, but my guess is that still no suerte con edgeRs1

**Comment by jcsteh** [comment]
It's worth noting that Windows now prevents NVDA from injecting its own code into the Settings app (and many other apps). Therefore, NVDA cannot directly cause a crash. That means this is probably due to a UIA implementation bug in Windows which is somehow triggered by NVDA but not Narrator.

@PratikP1, is this the bug you [mentioned on Twitter](https://twitter.com/ppatel/status/766635923681443840)?

**Comment by PratikP1** [comment]
This is exactly the bug I mentioned. Perhaps as a temporary fix, users can be alerted to use Narrator. The problem occurs if you’re trying to create a new account with Microsoft credentials or if you’re trying to add Microsoft credentials to an existing local account.

**Comment by jcsteh** [comment]
Microsoft are aware of this and have acknowledged it as a Microsoft bug.

**Comment by michaelDCurran** [comment]
Microsoft bug ID: 8775844

**Comment by derekriemer** [comment]
Is this fixed in creators update? If so may I close?

**Comment by josephsl** [comment]
Hi, not yet (overlay still closes).

**Comment by derekriemer** [comment]
@michaelDCurran @jcsteh @josephsl Any update on this from the good folks at microsoft? Will it be put into creators? #6872 was just opened as a duplicate.

**Comment by josephsl** [comment]
Hi,

Partially resolved (build 15031 at the moment):

1. Signing into a MS account: yes, you can now sign into apps and convert to an MS account with no issues.
2. Creating user accounts: Edge overlay closes, no issue with Narrator running.

Will file a feedback about the second issue. Thanks.

**Comment by gdata1** [comment]
If Microsoft recognized this as his mistake possible in the RS2 this will be corrected.

**Comment by michaelDCurran** [comment]
According to Microsoft, the actual fix (if they are correct) is not technically yet landed in an insider build. From what my contact at MS can see, it should land in 15036, so any insider build from that number on should have the fix. A lot of changes are happening to Edge at the moment, so it is possible that 15031 had code that  indirectly avoided the bug in some instances. MS however believes the actual bug stems from a UIA core issue.

**Comment by gdata1** [comment]
Hello. Windows 10 15046 problem not fixed.

**Comment by jcsteh** [comment]
This is fixed for me in build 15058.
