### ISSUE TITLE
Input braille: problem with signs on multiple cells and computer braille tables

### ISSUE THREAD

**Issue by aaclause** [nvaccess/nvda#7381]
First, let me list the next definitions in french braille (it's necessary to understand the following examples):

* ⠂ (dot2) = , — ⠒ (dots25) = : — ⠖ (dots235) = !
* ⠐ (dot5) = ´ (U+B4) — ⠘ (dots45) = ¤ (U+A4) — ⠸ (dots456) = ¸ (U+B8) — ⠨ = ¨ (U+A8; also capital sign in 6 dots braille)
* ⠁ (dot1) = a — ⠃ (dots12) = b.

AND

- "¤!" (⠘⠖) = ∩ (U+2229) — "¤¤!" (⠘⠘⠖) = ⋂ (U+22C2)
- "¸!" (⠸⠖) = ∪ (U+222A) — "¸¸!" (⠸⠸⠖) = ⋃ (U+22C3)
- "´:" (⠐⠒) = ⇐ — "´:," (⠐⠒⠂) = ⇔
- "¤a" (⠘⠁) = α (U+3B1) — "¨¤a" (⠨⠘⠁) = Α (U+391)

-------

Since Liblouis 3.2 was implemented*, in braille input, there are several bad translations when we type signs on multiple cells. Review some following examples:

- Input: ⠘⠖⠀
- Expected output: "¤! " (simple interpretation) or "∩ " (ideally / advanced interpretation)
- Actual output: "¤ "
- Detail: I type "⠘⠖⠀". My braille display shows "⠘⣏⠖ ⣹" temporarily. Then, I press space key and only "¤ " is printed.

Same problem with:
- Input: ⠁⠘⠖⠃
- Expected output: "a¤!b" or "a∩b" (ideally)
- Detail: I type "⠁⠘⠖⠃". My braille display shows "⠁⠘⣏⠖ ⣹⠃" temporarily. Only "a¤b" is printed.

Other examples:
- Input: ⠐⠒⠀ — output: "´ "
- Input: ⠨⠘⠁⠀ — output: "¨¤ "
- Input: ⠸⠖⠀ — output: "¸ "
- etc.

-------

Now, if I remove the next definitions in fr-bfu-comp8.utb:

> sign ¤ 45
> sign ¸ 456
> sign ´ 5
> sign ¨ 46
 
... next inputs give the good output:

* Input: ⠘⠖  — output: ∩
* Input: ⠸⠖  — output: ∪
* Input: ⠸⠸⠖ — output: ⋃
* Input: ⠐⠒  — output: ⇐
* Input: ⠨⠘⠁ — output: Α

... But there is the same problem with ⠐⠒⠂ for example, because ⠐⠒ has priority on him:

- Input: ⠐⠒⠂
- Expected output: "´:," or ⇔ (ideally)
- Actual output: "⇐"

Moreover, it's very annoying because we have not a translation for "¤", "¸", "´" and "¨".

-------

Remarks:

- with contracted unified french Table  (fr-bfu-g2.ctb), all is right;
- all signs on multiple cells are defined in "fr-bfu-comp68.cti".
- "fr-bfu-comp6.cti" is included in "fr-bfu-comp8.utb" and "fr-bfu-comp6.utb".

(*) "fr-bfu-comp6.cti" definitions are present since Liblouis 3.1.

**Comment by jcsteh** [comment]
Thanks for the thorough details. It's a lot to digest, so I'm not sure I
fully understand this. However, it sounds like in French, even in computer
braille, later braille cells can affect the interpretation of earlier
cells, even though the earlier cells do mean something when they occur
alone. The only way we can handle this is to have NVDA treat this table as
a contracted braille table, since we need the user to complete a word
before we can accurately translate it. This is a fairly easy change to
make, but it does mean it won't behave like most computer braille tables;
i.e. you'll have to press space, enter or translate to translate what
you've typed.

**Comment by Andre9642** [comment]
Thanks for your reply. Sorry for this message difficult to digest, but my English is perfectible and the problem isn't easy to explain. :)

I agree with your suggestion. However, would it be possible to enter in the "temporary mode" only when one of the following dot braille combinations is typed? ⠐ (dot5), ⠨ (dots46), ⠸ (dots456), ⠘ (dots45), ⠒ (dots25), ⠄ (dot3), and ⠶ (dots2356).
This might disturb most people who are used to a real-time display. Pressing constantly space or enter to see the word printed on the screen could be painful.

**Comment by jcsteh** [comment]
[**@Andre9642**](https://github.com/Andre9642) commented on [12 Jul 2017, 03:57 GMT+10](https://github.com/nvaccess/nvda/issues/7381#issuecomment-314523514 "2017-07-11T17:57:13Z - Replied by Github Reply Comments"):
> Thanks for your reply. Sorry for this message difficult to digest, but my English is perfectible and the problem isn't easy to explain. :)

No; it's not a problem with your English. It's just a complex problem and I didn't have the time to figure out the exact details of each example. However, i think we agree about the root cause of the problem.

> I agree with your suggestion. However, would it be possible to enter in the "temporary mode" only when one of the following dot braille combinations is typed?

Unfortunately not. That would require NVDA to hard-code special knowledge about dot patterns in various tables. That kind of information really should be kept in the table itself. Otherwise, maintenance becomes very difficult.

> This might disturb most people who are used to a real-time display. Pressing constantly space or enter to see the word printed on the screen could be painful.

That's unfortunately true. However, even if we did engage contracted mode just for the braille patterns you mentioned, users would still experience this for the rest of the word every time they used one of those patterns. Realtime output just isn't possible unless we can be sure that later patterns won't change the output of earlier ones.

Ideally, we'd somehow adjust this table so that it doesn't produce output for those cells alone unless it's certain that the word is ending; e.g. followed by a space. However, I don't know of any way to do this, and even if there were a way, it would still break if one of those signs (e.g. ⠘) was right at the end of a document.

**Comment by leonardder** [comment]
@Andre9642: Could you please provide a status update as whether this issue still occurs?

**Comment by Andre9642** [comment]
Hi,
This problem is (very partially) solved in French table in question.
We have passed all definitions in `fr-bfu-comp68.cti` in `noback`. It is not very elegant, but it is the best compromise for now. As a result, we have the "simple interpretations".
I have some ideas to improve that (probably through an add-on), I hope to work on this soon...

**Comment by leonardder** [comment]
[**@Andre9642**](https://github.com/Andre9642) commented on [7 mei 2018 16:04 CEST](https://github.com/nvaccess/nvda/issues/7381#issuecomment-387075073 "2018-05-07T14:04:07Z - Replied by Github Reply Comments"):
> I have some ideas to improve that (probably through an add-on), I hope to work on this soon...

I'd discourage the use of an add-on if things can be improved in liblouis.

**Comment by Andre9642** [comment]
Yes, indeed. But if we remove all `noback` in `fr-bfu-comp68.cti` all works fine with Liblouis...

```
$ echo '⡁⠘⠖⡃ B⠸⠖⡉ ⠘⠁ ⠘⠃ ⠘⠙ ⠘⠛ ⠘⠼' | lou_translate tables/fr-bfu-comp8.utb  -b
A∩B B∪C α β δ γ ∅
```

But, on the other hand, simple interpretations can be useful too...

**Comment by Andre9642** [comment]
CC @egli @bertfrees

**Comment by bertfrees** [comment]
I read the thread but I'm not sure what you are asking us (Liblouis).

If I understand correctly, you want to get an immediate back-translation while you type braille, where either previous characters are corrected when needed, or where characters are temporarily held back if their translation is not certain yet (or something in between)?

I don't know how NVDA works and what users expect so it's hard for me to give a sensible comment. It seems to me that making corrections to already typed text would be something NVDA could do in theory, but I don't know what that means in practice. Holding back characters and flushing them at certain intervals is something NVDA already does, but it does not make sense to use anything other than whole words for these intervals. A generic solution would require Liblouis to have some kind of a "streaming" API where input is fed in character per character and output characters become available as soon as they are known.

**Comment by Andre9642** [comment]
@bertfrees Thanks for your contribution.
> you want to get an immediate back-translation while you type braille, where either previous characters are corrected when needed, or where characters are temporarily held back if their translation is not certain yet [...]?
The second proposal.

@leonardder I might have another lead, making some changes in `brailleInput.handler.translate()` and `brailleInput.handler._translate()`. Something like this:

```
def translate(self):
	if not self.useContractedForCurrentFocus: self.useContractedForCurrentFocus = True
	else:
		self._translate(True)
		if not self.table.contracted: self.useContractedForCurrentFocus = False
```

Just a thought, not tested yet...

**Comment by Adriani90** [comment]
@Andre9642 is this issue still reproducible in Liblouis 3.9? Did you have an opportunity to test that on a try build or so?

**Comment by Andre9642** [comment]
> @Andre9642 is this issue still reproducible in Liblouis 3.9?

Yes, this issue is still reproducible. However French Braille tables have been updated since awhile and it's harder to reproduce now.
To reproduce this, edit `./louis/tables/fr-bfu-comp68.cti` and remove the `noback` opcode from all rules.


> Did you have an opportunity to test that on a try build or so?

I am on alpha channel and it's updated. :)

**Comment by DrSooom** [comment]
@Andre9642: Is this issue still reproducible with [NVDA 2024.1](https://www.nvaccess.org/files/nvda/releases/2024.1/nvda_2024.1.exe) respectively Liblouis 3.28.0 – because of the following change:

> • Character definition and base rules are now always considered in the order in which they are defined in the table. In other words the topmost rule always wins. This fixes a number of problems and inconsistencies. Thanks to Bert Frees for the fix. 
> ◦ Fix a problem with compbrlAtCursor and compbrlLeftCursor that was reported by Daniel Mayr

Source: https://liblouis.io/liblouis/2023/12/04/liblouis-release-3.28.0.html

**Comment by Adriani90** [comment]
@aaclause, @burmancomp, @Emil-18 could you test if this issue is still occuring?

**Comment by michaelDCurran** [comment]
Closing this issue as it is either fully or partially fixed. Please feel free to reopen and clearly state the current situation and how it should be addressed.
