### ISSUE TITLE
NVDA does not move cursor when in libreoffice calc.

### ISSUE THREAD

**Issue by blindndangerous** [nvaccess/nvda#7618]
### Steps to reproduce:
Open libreoffice calc. Try to move around. Using arrow keys will not move the cursor, not even after pressing f2, escape and then arrows.

### Expected behavior:
NVDA should move around the cells, after pressing f2 and then escape.
### Actual behavior:
NVDA does not move around the cells, even after pressing f2, and then escape. It remains in the cell that was last used when exiting calc.
### System configuration:
NVDA version:
NVDA Next 14463,7dca66c4
NVDA Installed or portable:
Installed
Other information:
Rolling back to NVDA Next 14456,d8cc508f fixes the problem.
Windows version:
Windows10 64-bit, 1709 (OS Build 16288.1)
Name and version of other software in use when reproducing the issue:
Libreoffice calc
Version: 5.3.4.2 x64
Build ID: f82d347cccObe322489bf7da61 d7e4adl 3fe2ff3
### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
Yes. Rolling back one next version fixes the issue so that after opening calc and pressing f2 and then escape, the problem is fixed and I can move around. But I can only move after pressing f2, then escape.
[nvda error.txt](https://github.com/nvaccess/nvda/files/1319423/nvda.error.txt)
[nvda error.txt](https://github.com/nvaccess/nvda/files/1319424/nvda.error.txt)

**Comment by Qchristensen** [comment]
I was on LibreOffice 5.3.2 and reproduced this.  I then upgraded to LibreOffice 5.4.1.2, still using NVDA next 14463, and investigated further.  I found I could move one cell, sometimes two, then NVDA would freeze.  It did come back after 30 seconds or so.  I then started LibreOffice Calc and waited for awhile before trying to move, and looking back at my log, it had still frozen.  The movement was just a way of observing the freeze that takes place regardless.  Once the freeze has sorted itself out, restarting NVDA (with LibreOffice) still open, doesn't reproduce it, only restarting LIbreOffice does.  I did try starting LibreOffice without NVDA running, then waiting a few minutes and then starting NVDA, and that did produce the same effect.  This also happens with NVDA 2017.3 for me.  In fact, any build of NVDA seems to produce this for me (tried back to 2015.1)

**Comment by zahra21** [comment]
hello.

i am not completely familiar with cursor movement, but i use my favorite version of nvda (which is 2017.1) with my favorite version of libreoffice (which is 5.3.4.1 x86)
i can navigate in one calc file which i use,
arrow keys work for me and nvda does not freeze for me.

i even dont need to press f2, then scape to read cells using nvda.

did you try x86 version of libreoffice?

hope that help, God bless you all.

**Comment by blindndangerous** [comment]
No, I have not tried only the x86 version of libreoffice. I guess I could, but I usually stick to 64-bit versions if I can. I've been trying other next versions, some seem to work, some don't. The latest next version does not, and I had to roll back again. Unfortunately, I did not get the numbers of the version that did work. Will keep watching this. For now, I'm just staying on the next version that does work.

**Comment by zahra21** [comment]
i only use x86 version of libreoffice and dont have issue with calc.
i could not use calc 5.2, but the problem seems to be resolved in 5.3
which i have.
i use 5.3.4.1 forever!
God bless you all and his infinite mercy be for you.

On 10/10/17, blindndangerous <notifications@github.com> wrote:
> No, I have not tried only the x86 version of libreoffice. I guess I could,
> but I usually stick to 64-bit versions if I can. I've been trying other next
> versions, some seem to work, some don't. The latest next version does not,
> and I had to roll back again. Unfortunately, I did not get the numbers of
> the version that did work. Will keep watching this. For now, I'm just
> staying on the next version that does work.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/7618#issuecomment-335573719


-- 
we have not sent you but as a mercy to the entire creation.
holy quran, chapter 21, verse 107.
in the very authentic narration from prophet Mohammad is:
indeed, imam husayn is the beacon of guidance and the ark of salvation.
best website for studying islamic book in different languages
www.al-islam.org

**Comment by zahra21** [comment]
hello again.
i think the x86 version of libreoffice is more stable and also more accessible.
moreover, you can use it in both 32 and 64bit versions of windows!

**Comment by zahra21** [comment]
hello.
i am not completely familiar with using calc and cursor movement in calc, but i use my favorite version of nvda (which is 2017.2) with my favorite version of libreoffice (which is 5.3.4)
i tested also libreoffice 5.1.6 and confirm in this version, i can navigate in one calc file which i have,
arrow keys work for me and nvda does not freeze for me.
i even dont need to press f2, then scape to read cells using nvda.
my system is 32bit and will remain 32bit by the grace of God, i  only use x86 version of libreoffice and dont have issue with calc.
i found  some issues with calc 5.2, (not sure completely the reasons and cause) but it seems that the issues are resolved in libreoffice 5.3
but 5.3 and later, have some issues using screen review for reading messages and dialogs of libreoffice, which i found a solution for it in bugzilla which one of the developers mentioned, and if someone wishes to know, i wish to explane it!
but the solution only works in 5.3, not in 5.4 and later!
the problem started happening because of adding harfbuzz and new textLayout engine in libreoffice.
i think the x86 version of libreoffice is more stable and also more accessible.
moreover, you can use it in both 32 and 64bit versions of windows!
God bless you all and his infinite mercy be for you.

**Comment by Adriani90** [comment]
@Qchristensen can you still reproduce this with last versions?
If not, i suggest to close this issue considering @zahra21's comment above.

**Comment by Qchristensen** [comment]
I just tried this again with NVDA 2018.4beta3 and LibreOffice 6.1.3.2 (x64) and it seems to be behaving fine.  I can move around immediately upon opening LibreOffice calc - either a blank file, or opening an existing file.

Therefore I'm going to close this, but if anyone is still experiencing this on the current version (of either LibreOffice or NVDA), do comment.
