### ISSUE TITLE
NVDA reads items in the Navigation pane dropdown menu twice

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#8471]
### Steps to reproduce:
Open any folder you wish, press Alt+V then Tab, and then the space bar to open the Navigation pane dropdown menu. Then navigate with Up and Down. Alternatively, you may want to open any folder, press ALT+V followed by N to open the Navigation pane dropdown menu, then navigate with Up/Down.
### Actual behavior:
As we press the Down arrow to move down the list or press Up arrow to move upwards, NVDA reads each item twice. For instance, Expand to open folder  Expand to open folder, Show all folders  Show all folders, and Show Libraries  Show libraries.
### Expected behavior:
NVDA should read each item just once.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.2.1
#### Windows version:
Windows 10 Pro 64-Bit Version 1803 (OS Build 17134.137)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No, only 2018.2.1

**Comment by josephsl** [comment]
Hi, in this case, turning off object descriptions should fix the problem, as name and description are the same. Thanks.

**Comment by amirsol81** [comment]
Hi. I don't think disabling a feature to fix an issue is a good idea
anyway. If this is indeed an issue, it should be fixed without the
need to go to NVDA's Settings window to disable a useful feature.
Thanks.

**Comment by josephsl** [comment]
Hi, Agreed. I dealt with this exact problem in Windows 10 Start search results, and wrote a mitigation for that in my add-on. We need to gather more data before I present my fix as part of a pull request. Thanks.

**Comment by amirsol81** [comment]
Thanks, Joseph. BTW your Windows 10 App Essentials add-on rocks!
Thanks for the efforts and the time you devote to it.

**Comment by Adriani90** [comment]
This issue is still reproducible in NVDA 2019.1 and Windows 10 1809 update.

**Comment by amirsol81** [comment]
This is no longer duplicable with NVDA alpha-20005,14c2e2ec and Windows 10 Pro 64-Bit Version 2004 (OS Build 19041.207). So I suggest closing it.

**Comment by amirsol81** [comment]
Tested with the latest alpha and its still duplicable. The important point here is that if you have the NVDAExtensionGlobalPlugin installed, and "No object description inWindows ribbons" checked in NVDAMenu>Preferences>NVDA global commands extension...>Settings>Computer, the twice reading of the navigation pain items is no longer reproducible. As I'm using this add-on and it provides a fix for the issue, I thought NVDA has fixed it -- which isn't the case.
This is also the case with MS Word 2016: just open MS Word, press ALT+F, and use Up/Down arrows for navigation. NVDA reads each item twice.

**Comment by josephsl** [comment]
Hi, don’t tell me these are UIA objects… If they are, this isn’t the first time we are seeing UIA server implementation issues (name and description properties are the same). Thanks.

**Comment by Adriani90** [comment]
Yes this is the case I guess @josephsl. Still reproducible in Windows 10.

**Comment by Adriani90** [comment]
@amirsol81 are you still having this issue In NVDA 2025.3.1 or last 64bit alpha and Windows 11 24 H2 or 25 H2?

**Comment by amirsol81** [comment]
@Adriani90 No, this seems to be fixed in Windows 11 25H2 using both NVDA official and alphas.

**Comment by Adriani90** [comment]
Thanks for the update. Closing as works for me.
