### ISSUE TITLE
No braille feedback in Excel when editing directly in cell

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#9749]
### Steps to reproduce:
1. Open Excel 2016 (Office 365) and make sure "Allow editing directly in cells" is turned on in File --> Options --> Advanced.
2. Start typing.

### Actual behavior:
You receive speech output, but no feedback in braille.

### Expected behavior:
You receive both speech and braille feedback as you type.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.1.1
#### Windows version:
Windows 10 (1809)
#### Name and version of other software in use when reproducing the issue:
Excel 2016 32-bit (latest from Office 365 as of today)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, seen to be working in NVDA 2019.1.

**Comment by leonardder** [comment]
So, you're observing that this is a regression in a minor point release? That's interesting.
Could you also provide info about the contents of your display while editing, as well as about the focus object at the time of editing? A test with Alpha might also be helpful.

**Comment by dkager** [comment]
Yes, it looks like a regression in the minor release, but with Office 365 changing nearly every week I don't want to make that claim too firm.

The braille display continues to show the cell number, e.g. A1.

The focus object seems to be OK:

```
name: u'Edit Cell'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
```

When I start editing a cell and Alt+Tab away and then back into Excel the braille display shows the  entered text, but any additional text you enter does not show up until you Alt+Tab again. Using Backspace will update the braille display, but typing characters does not.

**Comment by bramd** [comment]
Confirmed here. If you toggle braille tethering to review and back to focus or automatic again, it shows the correct output.

**Comment by MarcoZehe** [comment]
Could this be a symptom of this long-standing issue that braille simply doesn't track properly when typing in Windows 10 Mail, sometimes Outlook, or any other UIA-enabled app, only if you move the caret with arrow keys, does it catch up? I am seeing this kind of behavior all over the place when using braille. You type a hundred or so characters, and braille just doesn't show them unless I press an arrow key once.

**Comment by dkager** [comment]
Good point. I see this in other Windows 10 apps too, such as Calendar. 
@leonardder Do we use UIA for the Excel edit fields?

**Comment by dkager** [comment]
Here is the developer information for the edit field. Looks like it is UIA.

```
name: u'Edit Cell'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x05958C70>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: RectLTWH(left=40, top=331, width=96, height=29)
value: None
appModule: <'excel' (appName u'excel', process ID 1100) at address 580a630>
appModule.productName: u'Microsoft Office'
appModule.productVersion: u'16.0.11629.20246'
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 198768
windowClassName: u'EXCEL7'
windowControlID: 0
windowStyle: 1460338688
windowThreadID: 7180
windowText: u'Book1'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x7f239d0 at 54e8940>
UIA automationID: CellEdit
UIA frameworkID: 
UIA runtimeID: (42, 198768, 4, 494)
UIA providerDescription: [pid:1100,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:mso.dll)]
UIA className: 
UIA patterns available: LegacyIAccessiblePattern, TextPattern
```

**Comment by MarcoZehe** [comment]
Yes, this is UIA.

Davy Kager <notifications@github.com> schrieb am So., 16. Juni 2019, 20:07:

**Comment by dkager** [comment]
Coming back to the suggestion that the problem is related to braille and UIA edit fields: I'm seeing similar prolems in OneNote (both desktop and Windows 10 app), Microsoft Edge and several other programs. So the behavior in Excel appears to be an example of a larger problem, as Marco said. Should we use one GitHub issue to track these problems?

**Comment by Adriani90** [comment]
If there are different cases with similar steps to reproduce and the cause seems to be the same, I suggest to create a meta issue for such problems.

**Comment by leonardder** [comment]
@dkager: DO you also see these Edge issues in 2019.1 or older?

Pretty sure that all these cases are fixed by #9660. WHen running NVDA with that patch applied, the problems are gone.

**Comment by dkager** [comment]
Interesting. Will that patch make 2019.2? My tests thus far were with 2019.1 and 2019.1.1.

**Comment by Sylvie42** [comment]
Hello,
Using NVDA 2020.3 and Office 365 for businesses version Microsoft Office 16.0.13231.20390
I have Windows 10 version Windows 1909 (version 18363.139)
When the checkbox on direct editing is checked, I have no feedback in Braille about what I am typing. The same while typing F2 to modifiy the cell.
When the checkbox is unchecked, everything is oK.
After contacting Microsoft, they answered I should contact NV Access for this bug.
Best
Sylvie

**Comment by Andre9642** [comment]
Same here (Office Professional Plus 2019 16.0.13231.20390). The bug also occurs with NVDA 2020.1 and 2020.2.
Temporary solution: after entering in edit mode, move to focus object (NVDA+backspace [laptop] or NVDA+numpadMinus [desktop]).

**Comment by Adriani90** [comment]
It seems this one still occurs for some people, i am reopening it.

**Comment by Adriani90** [comment]
@dkager, @Sylvie42, @aaclause could you please test in Excel and directly editing in cell with NVDA 2023.3 or last NVDA alpha? Are you still able to reproduce this issue?

**Comment by dkager** [comment]
AFAIK this issue still exists with UIA disabled, but not on all computers that I've tried. I would like to do a more thorough test, including with UIA enabled, but that will have to wait a little while.

**Comment by Adriani90** [comment]
@dkager did you get the chance to test this a bit more? How is it now behaving with NVDA 2024.1?

cc: @burmancomp maybe you can test as well if this issue is occuring for you?

**Comment by Adriani90** [comment]
@dkager did you get the chance to test this a bit more? How is it now behaving with NVDA 2024.1?

cc: @burmancomp maybe you can test as well if this issue is occuring for you?

**Comment by burmancomp** [comment]
I opened empty worksheet in excel 2019, and when "a1" was shown in braille, then I typed characters. They were shown in braille.

I think it happens more or less frequently that when opening excel for some reason worksheet is not active ("a1" is not shown). In that case I think likely braille is not updated. I think there is similar behavior in word as well.

**Comment by Adriani90** [comment]
@burmancomp could you check if editing directly in cells is enabled in your MS Excel advanced options?
If not, could you enable it and test again?

**Comment by burmancomp** [comment]
> @burmancomp could you check if editing directly in cells is enabled in your MS Excel advanced options? If not, could you enable it and test again?

It is enabled.

**Comment by Adriani90** [comment]
Thanks for testing. I am closing this issue as works for me, if anyone still has this problem they can comment and we can reopen.
The issue regarding focus not being in the excel sheet when opening it is quite tricky, there are a lot of situations where this happens and there is not really something NVDA can do about it. Microsoft needs to expose the foreground window properly and the keyboard focus should be redirected there after opening the window. So if you have some time, please report this to them.
