### ISSUE TITLE
error on switch language with alt+shift on windows 10

### ISSUE THREAD

**Issue by kianoosh-shakeri** [nvaccess/nvda#9816]
### Steps to reproduce:
press alt+shift to switch between keyboard languages, specially in a browser
### Actual behavior:
NVDA logs an error refering to that nvda fails to gain focus
Also it speaks the changed language twice. Like if I switch to persian, it announces my switch two times
### Expected behavior:
language be switched without a problem, without any errors and any focus loss
#### NVDA installed/portable/running from source:
protable
#### NVDA version:
2019.2 beta
#### Windows version:
Windows version: Windows 10Ver1903 (64-bit) build 18362.175
#### Name and version of other software in use when reproducing the issue:
specially tried on google chrome
#### Other information about your system:
lenovo laptop
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes. Previous beta 1

**Comment by josephsl** [comment]
Hi, have you tried using Windows+SPACE keys for switching languages? Thanks.

**Comment by kianoosh-shakeri** [comment]
Yeah. I did. I still get the same error. Here's the full error:
ERROR - eventHandler.executeEvent (09:28:04.618):
error executing event: gainFocus on <NVDAObjects.UIA.ListItem object at 0x050EEB30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 150, in executeEvent
  File "eventHandler.pyo", line 163, in doPreGainFocus
  File "api.pyo", line 107, in setFocusObject
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 501, in _get_container
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1202, in _get_parent
  File "NVDAObjects\__init__.pyo", line 97, in __call__
  File "C:\Users\kianoosh\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 192, in chooseNVDAObjectOverlayClasses
  File "NVDAObjects\UIA\__init__.pyo", line 741, in _getUIACacheablePropertyValue
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

**Comment by josephsl** [comment]
Hi, okay, how about restarting with add-ons disabled? I ask because the last bits indicate my own add-on may have been involved in this issue. Thanks.

**Comment by amirsol81** [comment]
I can also duplicate this bug.
For the record, it started with Win 10 1903, and is duplicable both with ALT+Shift and with Windows+Space. Moreover, it isn't limited to browsers. I can make it happen in all apps especially if I press ALT+Shift a couple of times quickly. It seems that with each press of this key stroke NVDA loses focus momentarily and immediately returns to the window or app which had the focus. If you press and hold down ALT, press and release Shift, wait for NVDA to read the new typing language -- which is BTW erroneously announced two or three times, and then release ALT, you'll hear the name of the focused window or app -- something which is similar to pressing ALT+Tab. Quite interestingly, if the error message above is logged, NVDA doesn't read the characters I type unless I press ALT+Tab to return the focus to the app. This is very serious and annoying -- especially for those who need to alter the typing language quite frequently, and doesn't affect other screen readers -- namely JAWS -- at all.
Finally, this can be duplicated with or without add-ons, and also affects NVDA 2019.1.

**Comment by amirsol81** [comment]
Joseph, as I mentioned in my first comment, it also happens without add-ons. I myself used to think that the Win 10 add-on might be involved, but disabling it has no effect on the bug.

**Comment by josephsl** [comment]
Hi, I think probably because an exception isn’t handled when trying to obtain some values via UIA. If that is the culprit, then I think it’d be best to locate the most detailed issue, because others are simply various ways to trigger this bug and thus they are duplicates. Thanks.

**Comment by JulienCochuyt** [comment]
The double announcement of the switched layout kept aside, I do not reproduce any of the faulty behavior you mention on Windows 10 version 1903 64 bits build 18362.329 with NVDA 2019.2
I daily use three different keyboard layouts, in two different language settings: English QWERTY, French AZERTY and French BÉPO, switching from English to French using `alt+space` and between both French layouts using `control+shift`.
I never encountered an error with these in the four years I've been using NVDA.

That is to say, what you are facing might be related to either your specific build of Windows (mine is slightly different) or perhaps the fact that Persian is displayed with non-latin characters in the systray, or is it?
Also, do you reproduce with earlier NVDA such as 2018.4.1?

Regarding the double announcement of the switched layout: NVDA actually does not doubles the announce. Windows does. Examine the tooltip provided in the systray for the layout switcher: Press `Windows+b` to focus the systray, the `left arrow` enough times to reach there, just before the clock.
You'll notice that the tool tip includes twice the country name.
Here is what I get, roughly translated from my French locale:

Layout 1:
> English (United States)
> Keyboard English (United States)
> To switch between input methods, press Windows+Space.

Layout 2:
> French (France)
> Keyboard French
> To switch between input methods, press Windows+Space.

Layout 3:
> French (France)
> Keyboard French (bépo)
> To switch between input methods, press Windows+Space.

That is:
> Language (Dialect)
> Keyboard layout
> Shortcut hint

It appears that when you switch your keyboard layout, what NVDA announces is what changed in this tooltip message. I would bet NVDA has no special process for that, it just announces whatever changes in systray tooltips.

In my case, when switching keyboard layouts, NVDA never announces the shortcut hint, because this text does not change, nor does it announce the word "Keyboard", which does not change either. It only announces the part that changed.
When I switch from layout 1 to layout 2, it announces "French (France) French", that is "Language (Dialect) Layout".
When I switch from layout 2 to layout 3, it only announces "French (bépo)", that is just "Layout", because "Language" did not change.

What is questionable here is: Should the systray tooltips announces be incremental or atomic? Is it right to announce only what changed instead of the whole message?
I guess it acts that way because faulty programs might often update their systray icon tooltip with an unchanged text, and reading the whole thing every time it happens would be very irritating.
I wonder though if only exactly identical tooltips should be ignored, and tooltips with any difference in content should be announced entirely.

Does anyone know why we indeed adopted that behavior in the first place?

**Comment by JulienCochuyt** [comment]
@kianoosh-shakeri, @amirsol81,
Could you please try to provide a log of the error on gain focus event with add-ons disabled?

@josephsl, I guess the element that gets focus might be the "Input Flyout" list.
When switching layouts using `windows+space`, the "Input Flyout" list gets displayed and this is what NVDA announces but it is quite tedious to move to for inspection.
When switching input language with `alt+shift` or layout within the selected language with `control+shift` and releasing the keys quickly, it does not get displayed and NVDA announces the systray icon tooltip incremental change.
However, when `alt` or `control` are held down after pressing `shift`, the "Input Flyout" list gets displayed. If you then hold down `shift` and release the other modifier, the "Input Flyout" list remains open and focused, ready for inspection. Then, arrow keys can be used to select the desired layout. It might then be noted that the currently active layout, although visibly marked as such, is not announced by NVDA (we probably miss to consider an UIA state there).

**Comment by amirsol81** [comment]
Hi Julien,

NVDA alpha-19051,054d7b29, on Windows 10 version 1903 (OS Build 18362.116)
Here's my log. It displays the text which appears after the "NVDA
initialized" message, and whatever I paste below is generated after I
get the described issues with ALT+Tab.

ERROR - eventHandler.executeEvent (22:03:43.549) - MainThread (6648):
error executing event: UIA_elementSelected on
<NVDAObjects.UIA.ListItem object at 0x0770EB10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1476, in event_UIA_elementSelected
  File "NVDAObjects\UIA\__init__.pyc", line 1638, in event_stateChange
  File "NVDAObjects\__init__.pyc", line 1077, in event_stateChange
  File "speech\__init__.pyc", line 255, in speakObjectProperties
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:03:43.569) - MainThread (6648):
error executing event: gainFocus on <NVDAObjects.UIA.ListItem object
at 0x074CD390> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "appModules\explorer.pyc", line 337, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1092, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 978, in reportFocus
  File "speech\__init__.pyc", line 409, in speakObject
  File "speech\__init__.pyc", line 255, in speakObjectProperties
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:03:45.039) - MainThread (6648):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem
object at 0x074CD390> with extra args of {'ch': 'ش'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1037, in event_typedCharacter
  File "speech\__init__.pyc", line 719, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 911, in _get_isProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:03:45.645) - MainThread (6648):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem
object at 0x074CD390> with extra args of {'ch': 'س'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1037, in event_typedCharacter
  File "speech\__init__.pyc", line 719, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 911, in _get_isProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:03:46.059) - MainThread (6648):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem
object at 0x074CD390> with extra args of {'ch': 'ی'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1037, in event_typedCharacter
  File "speech\__init__.pyc", line 719, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 911, in _get_isProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:03:46.403) - MainThread (6648):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem
object at 0x074CD390> with extra args of {'ch': 'ب'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1037, in event_typedCharacter
  File "speech\__init__.pyc", line 719, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 911, in _get_isProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:03:46.926) - MainThread (6648):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem
object at 0x074CD390> with extra args of {'ch': 'ل'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1037, in event_typedCharacter
  File "speech\__init__.pyc", line 719, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 911, in _get_isProtected
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 759, in
_getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418094, 'The callee (server [not server
application]) is not available and disappeared; all connections are
invalid. The call did not execute.', (None, None, None, 0, None))

**Comment by JulienCochuyt** [comment]
I just encountered for the first time a similar issue on LibreOffice Writer when switching layouts with `control+shift`.
Though, I haven't been able so far to reproduce and provide a relevant log.

**Comment by amirsol81** [comment]
Here it's a daily and frustrating struggle with NVDA and apps like 
Chrome, MS Word, Wordpad, etc.

**Comment by JulienCochuyt** [comment]
@amirsol81 wrote:
> Here it's a daily and frustrating struggle with NVDA and apps like Chrome, MS Word, Wordpad, etc.

I disagree. My life is so much easier since I switched to NVDA! (And btw., I also use Chrome as my main browser.)
For sure, there are many things to fix and enhance, but at least NVDA is open and as such offers the possibility to diagnose, workaround and improve.

**Comment by amirsol81** [comment]
@Julien Cochuyt

You are free to disagree, and that's beyond the point being discussed. 
ever since this issue cropped up, I had to switch to JAWS just to be 
able to type effortlessly and efficiently in more than one language. And 
yes, I go back and forth between JAWS and NVDA when it comes to typing 
stuff.

Hope this is resolved soon.

**Comment by Adriani90** [comment]
I can reproduce this in Chrome, however, this does not occur everytime but randomly. However, I think this does not have a visible impact for users of the stable version of NVDA at least I couldn't find one.
The other issue regarding the language being reported multiple times, this is still occuring in NVDA 2020.1 but I think there was another issue for that specifically.

**Comment by amirsol81** [comment]
@Adriani90 I can duplicate both issues with both NVDA 2020.1 and Alpha 20220. The first one is more pronounced in MS Word 2019 and Chrome although it affects, say, one out of every three or four tries.

**Comment by Adriani90** [comment]
The error is not reproducible anymore, I am testing in Version: alpha-21196,4840e5fb and Chrome 86.
Only the ouble announcement is still reproducible, bot only when holding alt key down and pressing shift multiple times while hearing the reporting until the end. I am closing this issue for now because the description focuses on the error which is not reproducible anymore. Please create a new issue regarding the double reporting of the language.

**Comment by amirsol81** [comment]
@Adriani90 It sure is duplicable with Chrome 86 and NVDA Alpha 21196 -- the latest Alpha I'm running at the moment. In fact I just encountered once on Chrome, and it's also duplicable in other apps such as MS Word. So please re-open it. I don't think issues should be closed before making sure if others can duplicate them.

**Comment by Adriani90** [comment]
Ok, strange. I have tested in apps like Outlook 365, Firefox 81 etc and I cannot reproduce this. But fair enough, I am reopening.
cc: @josephsl can you reproduce this?

**Comment by amirsol81** [comment]
Granted, oftentimes it requires repeated presses of ALT+SHIFT. Also I 
have 3 languages attached to ALT+SHIFT -- one being a right-to-left one. 
But it's definitely there especially if you press ALT+SHIFT several times.

**Comment by DraganRatkovich** [comment]
Hello,
I have same problem when using alt+shift in Win 10.
Also, nvda doesn't interrupt speech when pressing Win+space in windows 8.1 and win10

**Comment by josephsl** [comment]
Hi,

Coming back to this...

Besides fixig a problem where language switcher wasn't usable with mouse and touch, can anyone try reproducing this issue with Narrator so we can narrow this down a lot, ideally both on Windows 10 and 11?

Thanks.

**Comment by Adriani90** [comment]
I think the error posted in https://github.com/nvaccess/nvda/issues/9816#issuecomment-549015088
is relevant for this issue, i can reproduce it reliably in Windows 11 with NvDA 2023.2.
With Narator this issue is not reproducible.

**Comment by josephsl** [comment]
Hi,

2024 update: still reproducible with 2024.3 beta 2. Interestingly, this is reproducible if you press NVDA+Tab after pressing Alt+Shift (while holding down the Alt key). The last log fragment tells us that NVDA could not retrieve the focus information for the input switcher because it is no longer visible on the screen but NVDA thinks it can stil extract valuable information. Besides, I don't think input switcher moves system focus back to where you were when it disappears, and if that's the case, the issue now becomes a combination of NVDA and input handling UI code written inside Microsoft (if so, this complicates the picture a lot).

Thanks.

**Comment by amirsol81** [comment]
@josephsl Thanks for re-visiting this old issue. Just worth mentioning that while I can reproduce it with NVDA, JAWS doesn't have such a glitch. So it leads me into thinking that the issue is more on NVDA's side or the way it interacts with the language switcher.

**Comment by josephsl** [comment]
Hi,

More specifically, how NVDA does not realize that the UIA element is no longer visible...

Thanks for validating the justification for revisiting this old issue (I'm commenting on ones with no comments since mid-2019).

**Comment by zstanecic** [comment]
I can still reproduce it, too even with the last alpha snapshot. The most annoying thing is, that even the language switcher in such situation lags horribly on windows 11, 24h2. I should say, that even Zdsr doesn't have the problem with switching keyboards.

**Comment by amirsol81** [comment]
It seems that NVDA is the only screen reader out there which displays such an issue.

**Comment by Adriani90** [comment]
User impact>
If you have speak typed characters on, NVDA will not announce them at all, but they will be still entered in the edit field. See #12373 for a use case.

cc: @msftedad I think Microsoft needs to provide a window handle for the keyboard language switch, especially when holding down alt+shift then the window appears but it is not recognized by NVDA as such probably it is not properly exposed.
Can you please take this with the development team?

**Comment by msftedad** [comment]
@Adriani90, We have forwarded this issue to development team. We will provide you with the tracking id once we receive update from them. Thanks

**Comment by msftedad** [comment]
@Adriani90, This issue is not repro'ing at our end. User is able to switch between languages using Left Alt+shift.
We have investigated the issue in the following version:
Windows Version: 24H2(OS Build 26100.2454)
NVDA 2024.4

Please refer to the attachment.

https://github.com/user-attachments/assets/fedf5103-e674-4bc5-885a-e3e4ec130e4b

**Comment by Adriani90** [comment]
@msftedad I reproduce this as follows:
1. Open NVDA
2. Focus an edit field )((e.g. the comment edit field)
3. Enable focus mode with NVDA+space bar
4. Press and hold alt key
5. Press shift key and release it, keep the alt key pressed
6. You will hear a list with alnguages appearing, NVDA will announce the currently selected language and its count (e.g. english 1 of 4)
7. Release the alt key
8. Type any character in the edit field you are focusing
9. Press escape to leave the focus mode, or press NVDA+space bar

Actual: 
* In step 8, error is played and no character is announced when typing, but it is visible that characters are typed in the edit field
* In step 9, NVDA cannot leave focus mode


Here is a screen cast of what I am doing:

https://github.com/user-attachments/assets/3227c524-6611-4015-9855-2034c25354a9

**Comment by Adriani90** [comment]
I am on Windows 11 23 H2 by the way.

**Comment by amirsol81** [comment]
@msftedad I can reliably duplicate this with NVDA Alpha 24627 on Windows 11 24H4 (26100.2454) following the steps which @Adriani90 outlined.

**Comment by amirmahdifard** [comment]
it's happening stil for me. I'm used to here the leters i type, but when I press alt+shift, sometimes randomly and i have to alt tab back to the window to gain back my focuss properly again. But my question is, if you think the problem is from windows, then why jaws has no problem with this?
